use_default_settings: true

general:
  debug: false
  instance_name: "Cybernaut Private Search"

search:
  safe_search: 1
  formats:
    - html
    - json

server:
  secret_key: "overridden-by-SEARXNG_SECRET"
  limiter: false
  image_proxy: true
  bind_address: "0.0.0.0"
  port: 8080
