import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { EyeOff } from 'lucide-react'
import { apiGet, apiPost } from '../lib/api'
import { useAuthStore } from '../store/useAuthStore'
import { Button, Card, Modal } from './ui'
import { useToast } from './Toast'
import { FdeTimeGrid, type TimeProposal } from './FdeTimeGrid'
import { FdeCompanyCalendar } from './FdeCompanyCalendar'
import { FdeLeaderTimePanel } from './FdeLeaderTimePanel'
import { shanghaiToday, shiftDate, weekStartFor } from '../../server/src/contracts/fdeWeeklyPlanContract'
import { calendarDefinitionSchema, timeInstant, timeLocal } from '../../server/src/contracts/fdeTimeContract'

type Item = { key:string;id:string|null;source:string;title:string;detail:string;projectName?:string|null;ownerId:string;ownerName:string;startsAt:string;endsAt:string|null;allDay:boolean;version:number|null;sourceVersion?:number;visibility?:string;editable:boolean;target:string|null }
type Calendar = {items:Item[];notice:string}
const blank = () => ({clientRequestId:crypto.randomUUID(),title:'',detail:'',startsAt:`${shiftDate(shanghaiToday(),1)}T10:00`,endsAt:`${shiftDate(shanghaiToday(),1)}T11:00`,visibility:'private' as 'private'|'company',reason:''})
export function FdeCalendarPanel({initialWeek, initialLayer = 'personal', allowLeader = true, companyOnly = false, compact = false, onHide}:{initialWeek?:string; initialLayer?:'personal'|'leader'; allowLeader?:boolean; companyOnly?:boolean; compact?:boolean; onHide?:()=>void}) {
  const userId = useAuthStore(state => state.user?.id ?? '')
  return <CalendarForAccount key={`${userId}:${initialLayer}:${companyOnly}:${compact}`} initialWeek={initialWeek} initialLayer={initialLayer} allowLeader={allowLeader} companyOnly={companyOnly} compact={compact} onHide={onHide} />
}
function CalendarForAccount({initialWeek, initialLayer, allowLeader, companyOnly, compact, onHide}:{initialWeek?:string; initialLayer:'personal'|'leader'; allowLeader:boolean; companyOnly:boolean; compact:boolean; onHide?:()=>void}) {
  const userName = useAuthStore(state => state.user?.name ?? '我的日历')
  const [layer, setLayer] = useState(initialLayer)
  const navigate=useNavigate(),{showToast}=useToast(),[week,setWeek]=useState(initialWeek??weekStartFor(shanghaiToday())),[view,setView]=useState<'personal'|'company'>(companyOnly?'company':'personal'),[includeMilestones,setIncludeMilestones]=useState(false),[data,setData]=useState<Calendar|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dialog,setDialog]=useState<{item?:Item;cancel?:boolean}|null>(null),[form,setForm]=useState(blank)
  const endpoint=`/calendar?weekStart=${week}&view=${view}&includeMilestones=${includeMilestones}`
  useEffect(() => { if (initialWeek) setWeek(initialWeek) }, [initialWeek])
  async function reload(){const next=await apiGet<Calendar>(endpoint);setData(next);setError('')}
  useEffect(()=>{let cancelled=false;setData(null);void apiGet<Calendar>(endpoint).then(next=>{if(!cancelled){setData(next);setError('')}}).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[endpoint])
  function field(key:string,value:string){setForm(previous=>({...previous,[key]:value,clientRequestId:crypto.randomUUID()}))}
  function open(item?:Item,cancel=false,proposal?:TimeProposal){
    if(proposal&&(!Number.isFinite(timeInstant(proposal.startsAt).getTime())||!Number.isFinite(proposal.durationMinutes)||proposal.durationMinutes<=0||proposal.durationMinutes>1440)){showToast('调整后的时间范围无效，请重新选择','error');return}
    setDialog({item,cancel});setForm({...blank(),...(item?{title:item.title,detail:item.detail,visibility:item.visibility==='company'?'company' as const:'private' as const,startsAt:timeLocal(new Date(item.startsAt)),endsAt:timeLocal(new Date(item.endsAt!))}:{}),...(proposal?{startsAt:proposal.startsAt,endsAt:timeLocal(new Date(timeInstant(proposal.startsAt).getTime()+proposal.durationMinutes*60000))}:{})})
  }
  function createAt(startsAt:string){open(undefined,false,{id:'new',startsAt,durationMinutes:60,method:'drag'})}
  const definition={title:form.title,detail:form.detail,startsAt:form.startsAt,endsAt:form.endsAt,visibility:form.visibility}
  function taskScheduleBody(item:Item,startsAt:string,endsAt:string,hidden:boolean,reason:string){return{clientRequestId:crypto.randomUUID(),expectedVersion:item.version??0,sourceVersion:item.sourceVersion,startsAt,endsAt,hidden,reason}}
  async function submit(){if(!dialog)return;setBusy(true);try{const item=dialog.item;if(item?.source==='task')await apiPost(`/calendar/tasks/${item.id}/schedule`,taskScheduleBody(item,form.startsAt,form.endsAt,Boolean(dialog.cancel),dialog.cancel?form.reason:'本人修改任务排期'));else if(dialog.cancel)await apiPost(`/calendar/${item!.id}/cancel`,{clientRequestId:form.clientRequestId,expectedVersion:item!.version,reason:form.reason});else await apiPost(item?`/calendar/${item.id}/save`:'/calendar',{clientRequestId:form.clientRequestId,...(item?{expectedVersion:item.version}:{}),definition});await reload();setDialog(null);showToast(dialog.cancel?'任务已从时间轴移除':'任务排期已保存')}catch(e){showToast((e as Error).message,'error');await reload().catch(()=>{})}finally{setBusy(false)}}
  async function applyProposal(proposal:TimeProposal){const item=data?.items.find(value=>value.id===proposal.id&&value.editable);if(!item||!item.endsAt||busy)return;const endsAt=timeLocal(new Date(timeInstant(proposal.startsAt).getTime()+proposal.durationMinutes*60000));setBusy(true);try{if(item.source==='task')await apiPost(`/calendar/tasks/${item.id}/schedule`,taskScheduleBody(item,proposal.startsAt,endsAt,false,proposal.method==='resize'?'本人拉伸任务时长':'本人移动任务时间'));else await apiPost(`/calendar/${item.id}/save`,{clientRequestId:crypto.randomUUID(),expectedVersion:item.version,definition:{title:item.title,detail:item.detail,startsAt:proposal.startsAt,endsAt,visibility:item.visibility==='company'?'company':'private'}});await reload();showToast(proposal.method==='resize'?'任务时长已更新':'任务时间已更新')}catch(e){showToast((e as Error).message,'error');await reload().catch(()=>{})}finally{setBusy(false)}}
  return <div className={`fde-workspace fde-collab-calendar ${compact?'fde-collab-calendar-compact':''}`}>
    <div className="fde-collab-calendar-scope"><strong>{compact?'任务时间轴':'公司内置日历'}</strong><div className="fde-collab-calendar-actions">{!compact&&<div className="fde-collab-segmented" aria-label="日历范围">{!companyOnly&&<button aria-pressed={view==='personal'} onClick={()=>setView('personal')}>我的日历</button>}<button aria-pressed={view==='company'} onClick={()=>setView('company')}>公司总表</button></div>}<div className="fde-collab-week"><button aria-label="上一周" onClick={()=>setWeek(shiftDate(week,-7))}>‹</button><button onClick={()=>setWeek(weekStartFor(shanghaiToday()))}>本周</button><button aria-label="下一周" onClick={()=>setWeek(shiftDate(week,7))}>›</button><input aria-label="日历周日期" type="date" value={week} onChange={event=>{if(event.target.value)setWeek(weekStartFor(event.target.value))}} /></div>{compact&&onHide&&<button className="fde-calendar-hide" type="button" title="隐藏时间轴" aria-label="隐藏时间轴" onClick={onHide}><EyeOff size={17}/></button>}</div></div>
    {view==='personal'&&allowLeader&&<div className="fde-collab-calendar-layer"><strong>个人时间视图</strong><div className="fde-collab-segmented"><button aria-pressed={layer==='personal'} onClick={()=>setLayer('personal')}>我的安排</button><button aria-pressed={layer==='leader'} onClick={()=>setLayer('leader')}>领导时间</button></div></div>}
    {view==='personal'&&layer==='leader'?<FdeLeaderTimePanel initialWeek={week}/>:<section className="fde-collab-card fde-collab-calendar-card"><div className="fde-collab-card-head"><h2>{view==='personal'?userName:'全公司日程'} · {week}—{shiftDate(week,view==='company'?4:6)}</h2><div className="fde-collab-calendar-actions">{view==='personal'&&<><div className="fde-collab-legend"><span><i/>个人安排</span><span><i data-tone="pending"/>暂定</span><span><i data-tone="locked"/>任务 / 会议</span></div><Button onClick={()=>open()}>添加安排</Button></>}</div></div>
      {error&&<div role="alert" className="fde-collab-state">{error}<Button variant="secondary" onClick={()=>void reload().catch(e=>setError(e.message))}>重试</Button></div>}{!data&&!error&&<div className="fde-collab-state" role="status">正在读取真实日历来源…</div>}
      {data&&(view==='company'?<FdeCompanyCalendar week={week} items={data.items}/>:<FdeTimeGrid weekStart={week} items={data.items} onCreateAt={createAt} onOpen={key=>{const item=data.items.find(v=>v.key===key);if(item?.editable)open(item);else if(item?.target)navigate(item.target)}} onPropose={proposal=>void applyProposal(proposal)} />)}
    </section>}
    <details className="fde-collab-tools"><summary>日历来源、日期标记与全部事项</summary><div><Button variant="secondary" onClick={()=>void reload().catch(e=>setError(e.message))}>刷新日历</Button><label><input type="checkbox" checked={includeMilestones} onChange={event=>setIncludeMilestones(event.target.checked)}/>显示已批准节点日期（不占用时间）</label><p>{data?.notice}</p><p>本人任务和个人安排可移动、拉伸、修改或移出时间轴；会议等其他业务日程需在其来源页面修改。</p></div>
<Card className="p-5"><h3 className="font-semibold">本周事项（含全天、截止点与非工作时段）</h3><div className="mt-3 space-y-3">{data?.items.length===0&&<p className="text-sm text-slate-500">本周暂无可展示的安排。</p>}{data?.items.map(item=><article className="rounded-lg border border-slate-200 p-4" key={item.key}><div className="flex flex-wrap items-center justify-between gap-2"><h4 className="text-sm font-medium">{item.title}</h4><span className="text-xs text-slate-500">{item.ownerName} · {item.editable?(item.source==='task'?'本人任务排期':'本人独立安排'):'只读'}</span></div><p className="mt-2 text-xs text-slate-600">{item.source==='milestone'?timeLocal(new Date(item.startsAt)).slice(0,10):timeLocal(new Date(item.startsAt)).replace('T',' ')}{item.endsAt?` — ${timeLocal(new Date(item.endsAt)).replace('T',' ')}`:item.source==='milestone'?' · 节点日期标记':item.allDay?' · 当日截止':' · 截止点/结束时间未记录'}</p>{item.detail&&<p className="mt-2 whitespace-pre-wrap text-sm text-slate-500">{item.detail}</p>}<div className="mt-3 flex gap-2">{item.editable&&<><Button variant="secondary" disabled={busy} onClick={()=>open(item)}>{item.source==='task'?'编辑任务时间':'编辑安排'}</Button><Button variant="secondary" disabled={busy} onClick={()=>open(item,true)}>{item.source==='task'?'移出时间轴':'取消安排'}</Button></>}{item.target&&<Button variant="secondary" onClick={()=>navigate(item.target!)}>打开来源</Button>}</div></article>)}</div></Card>
    </details>
    <Modal open={Boolean(dialog)} title={dialog?.cancel?'删除任务':dialog?.item?'编辑任务':'新建任务'} onClose={()=>{if(!busy)setDialog(null)}} footer={<>{dialog?.item&&!dialog.cancel&&<Button variant="secondary" disabled={busy} onClick={()=>open(dialog.item,true)}>删除任务</Button>}<Button variant="secondary" disabled={busy} onClick={()=>setDialog(null)}>取消</Button><Button loading={busy} disabled={dialog?.cancel?form.reason.trim().length<2:!calendarDefinitionSchema.safeParse(definition).success} onClick={()=>void submit()}>{dialog?.cancel?'确认删除':'保存任务'}</Button></>}>
      <div className="space-y-4">{dialog?.cancel?<label className="block"><span className="label">删除原因</span><textarea className="textarea w-full" value={form.reason} onChange={e=>field('reason',e.target.value)} /></label>:<><label className="block"><span className="label">任务名称</span><input className="input w-full" disabled={dialog?.item?.source==='task'} value={form.title} onChange={e=>field('title',e.target.value)} /></label><label className="block"><span className="label">任务说明</span><textarea className="textarea w-full" disabled={dialog?.item?.source==='task'} value={form.detail} onChange={e=>field('detail',e.target.value)} /></label>{(['startsAt','endsAt'] as const).map((key,i)=><label className="block" key={key}><span className="label">{i?'结束':'开始'}时间（上海时间）</span><input type="datetime-local" step={900} className="input w-full" value={form[key]} onInput={e=>field(key,e.currentTarget.value)} onChange={e=>field(key,e.target.value)} /></label>)}{dialog?.item?.source!=='task'&&<label className="block"><span className="label">可见范围</span><select className="input w-full" value={form.visibility} onChange={e=>field('visibility',e.target.value)}><option value="private">仅本人可见详情</option><option value="company">公司可见标题和说明</option></select></label>}</>}</div>
    </Modal>
  </div>
}
