import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { apiGet, apiPost } from '../lib/api'
import { useAuthStore } from '../store/useAuthStore'
import { Button, Card, Modal } from './ui'
import { useToast } from './Toast'
import { FdeTimeGrid, type TimeProposal } from './FdeTimeGrid'
import { FdeCompanyCalendar } from './FdeCompanyCalendar'
import { FdeLeaderTimePanel } from './FdeLeaderTimePanel'
import { shanghaiToday, shiftDate, weekStartFor } from '../../server/src/contracts/fdeWeeklyPlanContract'
import { calendarDefinitionSchema, timeInstant, timeLocal } from '../../server/src/contracts/fdeTimeContract'

type Item = { key:string;id:string|null;source:string;title:string;detail:string;ownerId:string;ownerName:string;startsAt:string;endsAt:string|null;allDay:boolean;version:number|null;visibility?:string;editable:boolean;target:string|null }
type Calendar = {items:Item[];notice:string}
const blank = () => ({clientRequestId:crypto.randomUUID(),title:'',detail:'',startsAt:`${shiftDate(shanghaiToday(),1)}T10:00`,endsAt:`${shiftDate(shanghaiToday(),1)}T11:00`,visibility:'private' as 'private'|'company',reason:''})
export function FdeCalendarPanel({initialWeek, initialLayer = 'personal', allowLeader = true, companyOnly = false}:{initialWeek?:string; initialLayer?:'personal'|'leader'; allowLeader?:boolean; companyOnly?:boolean}) {
  const userId = useAuthStore(state => state.user?.id ?? '')
  return <CalendarForAccount key={`${userId}:${initialLayer}:${companyOnly}`} initialWeek={initialWeek} initialLayer={initialLayer} allowLeader={allowLeader} companyOnly={companyOnly} />
}
function CalendarForAccount({initialWeek, initialLayer, allowLeader, companyOnly}:{initialWeek?:string; initialLayer:'personal'|'leader'; allowLeader:boolean; companyOnly:boolean}) {
  const userName = useAuthStore(state => state.user?.name ?? '我的日历')
  const [layer, setLayer] = useState(initialLayer)
  const navigate=useNavigate(),{showToast}=useToast(),[week,setWeek]=useState(initialWeek??weekStartFor(shanghaiToday())),[view,setView]=useState<'personal'|'company'>(companyOnly?'company':'personal'),[includeMilestones,setIncludeMilestones]=useState(false),[data,setData]=useState<Calendar|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dialog,setDialog]=useState<{item?:Item;cancel?:boolean}|null>(null),[form,setForm]=useState(blank)
  const endpoint=`/calendar?weekStart=${week}&view=${view}&includeMilestones=${includeMilestones}`
  useEffect(() => { if (initialWeek) setWeek(initialWeek) }, [initialWeek])
  async function reload(){const next=await apiGet<Calendar>(endpoint);setData(next);setError('')}
  useEffect(()=>{let cancelled=false;setData(null);void apiGet<Calendar>(endpoint).then(next=>{if(!cancelled){setData(next);setError('')}}).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[endpoint])
  function field(key:string,value:string){setForm(previous=>({...previous,[key]:value,clientRequestId:crypto.randomUUID()}))}
  function open(item?:Item,cancel=false,proposal?:TimeProposal){
    if(proposal&&(!Number.isFinite(timeInstant(proposal.startsAt).getTime())||!Number.isFinite(proposal.durationMinutes)||proposal.durationMinutes<=0||proposal.durationMinutes>1440)){showToast('调整后的时间范围无效，请重新选择','error');return}
    setDialog({item,cancel});setForm({...blank(),...(item?{title:item.title,detail:item.detail,visibility:item.visibility==='company'?'company' as const:'private' as const,startsAt:timeLocal(new Date(item.startsAt)),endsAt:timeLocal(new Date(item.endsAt!))}:{}),...(proposal?{startsAt:proposal.startsAt,endsAt:timeLocal(new Date(timeInstant(proposal.startsAt).getTime()+proposal.durationMinutes*60000))}:{})})
  }
  const definition={title:form.title,detail:form.detail,startsAt:form.startsAt,endsAt:form.endsAt,visibility:form.visibility}
  async function submit(){if(!dialog)return;setBusy(true);try{if(dialog.cancel)await apiPost(`/calendar/${dialog.item!.id}/cancel`,{clientRequestId:form.clientRequestId,expectedVersion:dialog.item!.version,reason:form.reason});else await apiPost(dialog.item?`/calendar/${dialog.item.id}/save`:'/calendar',{clientRequestId:form.clientRequestId,...(dialog.item?{expectedVersion:dialog.item.version}:{}),definition});await reload();setDialog(null);showToast(dialog.cancel?'个人安排已取消，原业务对象不变':'个人安排已保存')}catch(e){showToast((e as Error).message,'error');await reload().catch(()=>{})}finally{setBusy(false)}}
  return <div className="fde-workspace fde-collab-calendar">
    <div className="fde-collab-calendar-scope"><strong>公司内置日历</strong><div className="fde-collab-calendar-actions"><div className="fde-collab-segmented" aria-label="日历范围">{!companyOnly&&<button aria-pressed={view==='personal'} onClick={()=>setView('personal')}>我的日历</button>}<button aria-pressed={view==='company'} onClick={()=>setView('company')}>公司总表</button></div><div className="fde-collab-week"><button aria-label="上一周" onClick={()=>setWeek(shiftDate(week,-7))}>‹</button><button onClick={()=>setWeek(weekStartFor(shanghaiToday()))}>本周</button><button aria-label="下一周" onClick={()=>setWeek(shiftDate(week,7))}>›</button><input aria-label="日历周日期" type="date" value={week} onChange={event=>{if(event.target.value)setWeek(weekStartFor(event.target.value))}} /></div></div></div>
    {view==='personal'&&allowLeader&&<div className="fde-collab-calendar-layer"><strong>个人时间视图</strong><div className="fde-collab-segmented"><button aria-pressed={layer==='personal'} onClick={()=>setLayer('personal')}>我的安排</button><button aria-pressed={layer==='leader'} onClick={()=>setLayer('leader')}>领导时间</button></div></div>}
    {view==='personal'&&layer==='leader'?<FdeLeaderTimePanel initialWeek={week}/>:<section className="fde-collab-card fde-collab-calendar-card"><div className="fde-collab-card-head"><h2>{view==='personal'?userName:'全公司日程'} · {week}—{shiftDate(week,view==='company'?4:6)}</h2><div className="fde-collab-calendar-actions">{view==='personal'&&<><div className="fde-collab-legend"><span><i/>个人安排</span><span><i data-tone="pending"/>暂定</span><span><i data-tone="locked"/>任务 / 会议</span></div><Button onClick={()=>open()}>添加安排</Button></>}</div></div>
      {error&&<div role="alert" className="fde-collab-state">{error}<Button variant="secondary" onClick={()=>void reload().catch(e=>setError(e.message))}>重试</Button></div>}{!data&&!error&&<div className="fde-collab-state" role="status">正在读取真实日历来源…</div>}
      {data&&(view==='company'?<FdeCompanyCalendar week={week} items={data.items}/>:<FdeTimeGrid weekStart={week} items={data.items} onOpen={key=>{const item=data.items.find(v=>v.key===key);if(item?.editable)open(item);else if(item?.target)navigate(item.target)}} onPropose={proposal=>{const item=data.items.find(v=>v.id===proposal.id&&v.editable);if(item)open(item,false,proposal)}} />)}
    </section>}
    <details className="fde-collab-tools"><summary>日历来源、日期标记与全部事项</summary><div><Button variant="secondary" onClick={()=>void reload().catch(e=>setError(e.message))}>刷新日历</Button><label><input type="checkbox" checked={includeMilestones} onChange={event=>setIncludeMilestones(event.target.checked)}/>显示已批准节点日期（不占用时间）</label><p>{data?.notice}</p><p>个人安排可编辑；业务来源只读，无权日程仅显示占用。公司总表按已返回日程的成员展示；全天、跨周、周末及非工作时段事项保留在下方。</p></div>
<Card className="p-5"><h3 className="font-semibold">本周事项（含全天、截止点与非工作时段）</h3><div className="mt-3 space-y-3">{data?.items.length===0&&<p className="text-sm text-slate-500">本周暂无可展示的安排。</p>}{data?.items.map(item=><article className="rounded-lg border border-slate-200 p-4" key={item.key}><div className="flex flex-wrap items-center justify-between gap-2"><h4 className="text-sm font-medium">{item.title}</h4><span className="text-xs text-slate-500">{item.ownerName} · {item.editable?'本人独立安排':'只读'}</span></div><p className="mt-2 text-xs text-slate-600">{item.source==='milestone'?timeLocal(new Date(item.startsAt)).slice(0,10):timeLocal(new Date(item.startsAt)).replace('T',' ')}{item.endsAt?` — ${timeLocal(new Date(item.endsAt)).replace('T',' ')}`:item.source==='milestone'?' · 节点日期标记':item.allDay?' · 当日截止':' · 截止点/结束时间未记录'}</p>{item.detail&&<p className="mt-2 whitespace-pre-wrap text-sm text-slate-500">{item.detail}</p>}<div className="mt-3 flex gap-2">{item.editable&&<><Button variant="secondary" disabled={busy} onClick={()=>open(item)}>编辑安排</Button><Button variant="secondary" disabled={busy} onClick={()=>open(item,true)}>取消安排</Button></>}{item.target&&<Button variant="secondary" onClick={()=>navigate(item.target!)}>打开来源</Button>}</div></article>)}</div></Card>
    </details>
    <Modal open={Boolean(dialog)} title={dialog?.cancel?'取消个人安排':dialog?.item?'编辑个人安排':'新建个人安排'} onClose={()=>{if(!busy)setDialog(null)}} footer={<><Button variant="secondary" disabled={busy} onClick={()=>setDialog(null)}>取消</Button><Button loading={busy} disabled={dialog?.cancel?form.reason.trim().length<2:!calendarDefinitionSchema.safeParse(definition).success} onClick={()=>void submit()}>确认提交</Button></>}><div className="space-y-4">{dialog?.cancel?<label className="block"><span className="label">取消原因</span><textarea className="textarea w-full" value={form.reason} onChange={e=>field('reason',e.target.value)} /></label>:<><label className="block"><span className="label">事项标题</span><input className="input w-full" value={form.title} onChange={e=>field('title',e.target.value)} /></label><label className="block"><span className="label">事项说明</span><textarea className="textarea w-full" value={form.detail} onChange={e=>field('detail',e.target.value)} /></label>{(['startsAt','endsAt'] as const).map((key,i)=><label className="block" key={key}><span className="label">{i?'结束':'开始'}时间（上海时间）</span><input type="datetime-local" step={900} className="input w-full" value={form[key]} onInput={e=>field(key,e.currentTarget.value)} onChange={e=>field(key,e.target.value)} /></label>)}<label className="block"><span className="label">可见范围</span><select className="input w-full" value={form.visibility} onChange={e=>field('visibility',e.target.value)}><option value="private">仅本人详情，公司只看占用</option><option value="company">公司可见标题和说明</option></select></label><p className="text-xs text-slate-500">15 分钟步长，单项不超过 24 小时。取消个人安排不会删除或完成任何项目任务。</p></>}</div></Modal>
  </div>
}
