import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { EyeOff, Plus } from 'lucide-react'
import { apiGet, apiPost } from '../lib/api'
import { useAuthStore } from '../store/useAuthStore'
import { Button, Card, Modal } from './ui'
import { useToast } from './Toast'
import { FdeTimeGrid, type TimeProposal } from './FdeTimeGrid'
import { FdeCompanyCalendar } from './FdeCompanyCalendar'
import { FdeLeaderTimePanel } from './FdeLeaderTimePanel'
import { shanghaiToday, shiftDate, weekStartFor } from '../../server/src/contracts/fdeWeeklyPlanContract'
import { calendarDefinitionSchema, calendarTaskCreateSchema, timeInstant, timeLocal } from '../../server/src/contracts/fdeTimeContract'
import type { UnifiedTaskPrimaryAction } from '../../server/src/contracts/unifiedTaskContract'
import { HelpPopover, TaskDrawer } from './task/TaskSystem'

type Item = { key:string;id:string|null;source:string;title:string;detail:string;projectId?:string|null;projectName?:string|null;ownerId:string;ownerName:string;startsAt:string;endsAt:string|null;allDay:boolean;version:number|null;sourceVersion?:number;visibility?:string;editable:boolean;target:string|null }
type Calendar = {items:Item[];notice:string}
const blank = () => ({clientRequestId:crypto.randomUUID(),title:'',detail:'',startsAt:`${shiftDate(shanghaiToday(),1)}T10:00`,endsAt:`${shiftDate(shanghaiToday(),1)}T11:00`,visibility:'private' as 'private'|'company',reason:''})
export function FdeCalendarPanel({initialWeek, initialLayer = 'personal', allowLeader = true, companyOnly = false, compact = false, onHide}:{initialWeek?:string; initialLayer?:'personal'|'leader'; allowLeader?:boolean; companyOnly?:boolean; compact?:boolean; onHide?:()=>void}) {
  const userId = useAuthStore(state => state.user?.id ?? '')
  return <CalendarForAccount key={`${userId}:${initialLayer}:${companyOnly}:${compact}`} initialWeek={initialWeek} initialLayer={initialLayer} allowLeader={allowLeader} companyOnly={companyOnly} compact={compact} onHide={onHide} />
}
function CalendarForAccount({initialWeek, initialLayer, allowLeader, companyOnly, compact, onHide}:{initialWeek?:string; initialLayer:'personal'|'leader'; allowLeader:boolean; companyOnly:boolean; compact:boolean; onHide?:()=>void}) {
  const userId = useAuthStore(state => state.user?.id ?? 'anonymous')
  const userName = useAuthStore(state => state.user?.name ?? '我的日历')
  const weekendKey = `fde-calendar-weekends:${userId}`
  const [layer, setLayer] = useState(initialLayer)
  const [showWeekends, setShowWeekends] = useState(() => { try { return localStorage.getItem(weekendKey) === '1' } catch { return false } })
  const navigate=useNavigate(),{showToast}=useToast(),[week,setWeek]=useState(initialWeek??weekStartFor(shanghaiToday())),[view,setView]=useState<'personal'|'company'>(companyOnly?'company':'personal'),[includeMilestones,setIncludeMilestones]=useState(false),[data,setData]=useState<Calendar|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dialog,setDialog]=useState<{item?:Item;cancel?:boolean}|null>(null),[selectedTaskId,setSelectedTaskId]=useState<string|null>(null),[form,setForm]=useState(blank)
  const endpoint=`/calendar?weekStart=${week}&view=${view}&includeMilestones=${includeMilestones}`
  useEffect(() => { if (initialWeek) setWeek(initialWeek) }, [initialWeek])
  useEffect(() => { try { localStorage.setItem(weekendKey, showWeekends ? '1' : '0') } catch { /* preference remains active for this session */ } }, [showWeekends, weekendKey])
  async function reload(){const next=await apiGet<Calendar>(endpoint);setData(next);setError('')}
  useEffect(()=>{let cancelled=false;setData(null);void apiGet<Calendar>(endpoint).then(next=>{if(!cancelled){setData(next);setError('')}}).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[endpoint])
  function field(key:string,value:string){setForm(previous=>({...previous,[key]:value,clientRequestId:crypto.randomUUID()}))}
  function open(item?:Item,cancel=false,proposal?:TimeProposal){
    if(proposal&&(!Number.isFinite(timeInstant(proposal.startsAt).getTime())||!Number.isFinite(proposal.durationMinutes)||proposal.durationMinutes<=0||proposal.durationMinutes>1440)){showToast('调整后的时间范围无效，请重新选择','error');return}
    setDialog({item,cancel});setForm({...blank(),...(item?{title:item.title,detail:item.detail,visibility:item.visibility==='company'?'company' as const:'private' as const,startsAt:timeLocal(new Date(item.startsAt)),endsAt:timeLocal(new Date(item.endsAt!))}:{}),...(proposal?{startsAt:proposal.startsAt,endsAt:timeLocal(new Date(timeInstant(proposal.startsAt).getTime()+proposal.durationMinutes*60000))}:{})})
  }
  function createAt(startsAt:string){open(undefined,false,{id:'new',startsAt,durationMinutes:60,method:'drag'})}
  const definition={title:form.title,detail:form.detail,startsAt:form.startsAt,endsAt:form.endsAt,visibility:form.visibility}
  function taskScheduleBody(item:Item,startsAt:string,endsAt:string,hidden:boolean,reason:string){return{clientRequestId:crypto.randomUUID(),expectedVersion:item.version??0,sourceVersion:item.sourceVersion,startsAt,endsAt,hidden,reason}}
  async function submit(){if(!dialog)return;setBusy(true);try{const item=dialog.item;if(item?.source==='task'&&dialog.cancel){if(item.projectId)await apiPost(`/calendar/tasks/${item.id}/schedule`,taskScheduleBody(item,form.startsAt,form.endsAt,true,'本人从日历移除任务'));else await apiPost(`/calendar/tasks/${item.id}/cancel`,{clientRequestId:form.clientRequestId,expectedTaskVersion:item.sourceVersion,expectedScheduleVersion:item.version??0,reason:'本人删除个人事项'})}else if(item?.source==='task')await apiPost(`/calendar/tasks/${item.id}/schedule`,taskScheduleBody(item,form.startsAt,form.endsAt,false,'本人修改任务排期'));else if(dialog.cancel)await apiPost(`/calendar/${item!.id}/cancel`,{clientRequestId:form.clientRequestId,expectedVersion:item!.version,reason:'本人删除个人事项'});else if(!item)await apiPost('/calendar/tasks',{clientRequestId:form.clientRequestId,title:form.title,detail:form.detail,startsAt:form.startsAt,endsAt:form.endsAt});else await apiPost(`/calendar/${item.id}/save`,{clientRequestId:form.clientRequestId,expectedVersion:item.version,definition});await reload();setDialog(null);showToast(dialog.cancel?(item?.source==='task'&&item.projectId?'已从日历移除':'个人事项已删除'):'任务时间已保存')}catch(e){showToast((e as Error).message,'error');await reload().catch(()=>{})}finally{setBusy(false)}}
  async function applyProposal(proposal:TimeProposal){const item=data?.items.find(value=>value.id===proposal.id&&value.editable);if(!item||!item.endsAt||busy)return;const endsAt=timeLocal(new Date(timeInstant(proposal.startsAt).getTime()+proposal.durationMinutes*60000));setBusy(true);try{if(item.source==='task')await apiPost(`/calendar/tasks/${item.id}/schedule`,taskScheduleBody(item,proposal.startsAt,endsAt,false,proposal.method==='resize'?'本人拉伸任务时长':'本人移动任务时间'));else await apiPost(`/calendar/${item.id}/save`,{clientRequestId:crypto.randomUUID(),expectedVersion:item.version,definition:{title:item.title,detail:item.detail,startsAt:proposal.startsAt,endsAt,visibility:item.visibility==='company'?'company':'private'}});await reload();showToast(proposal.method==='resize'?'任务时长已更新':'任务时间已更新')}catch(e){showToast((e as Error).message,'error');await reload().catch(()=>{})}finally{setBusy(false)}}
  async function taskAction(action:string,task:{id:string;version:number;project:{id:string}|null}){if(!task.project)return;if(action==='not_started'){setBusy(true);try{await apiPost(`/projects/${task.project.id}/fde-tasks/${task.id}/start`,{expectedVersion:task.version});await reload();setSelectedTaskId(null);showToast('任务已开始')}catch(e){showToast((e as Error).message,'error')}finally{setBusy(false)};return}const route=action==='in_progress'||action==='returned'?'submission':action==='pending_acceptance'?'accept':action==='feedback'?'progress':action==='extension'||action==='cancel'?action:'';setSelectedTaskId(null);navigate(route?`/projects/${task.project.id}?tab=tasks&task=${task.id}&action=${route}`:`/projects/${task.project.id}?tab=tasks&task=${task.id}`)}
  return <div className={`fde-workspace fde-collab-calendar ${compact?'fde-collab-calendar-compact':''}`}>
    <div className="fde-collab-calendar-scope"><strong>{compact?'任务时间轴':'日历'}</strong><div className="fde-collab-calendar-actions">{!compact&&<div className="fde-collab-segmented" aria-label="日历范围">{!companyOnly&&<button aria-pressed={view==='personal'} onClick={()=>setView('personal')}>我的日历</button>}<button aria-pressed={view==='company'} onClick={()=>setView('company')}>公司总表</button></div>}<div className="fde-collab-week"><button aria-label="上一周" onClick={()=>setWeek(shiftDate(week,-7))}>‹</button><button onClick={()=>setWeek(weekStartFor(shanghaiToday()))}>本周</button><button aria-label="下一周" onClick={()=>setWeek(shiftDate(week,7))}>›</button><input aria-label="日历周日期" type="date" value={week} onChange={event=>{if(event.target.value)setWeek(weekStartFor(event.target.value))}} /></div>{view==='personal'&&layer==='personal'&&<button className="fde-weekend-toggle" type="button" aria-pressed={showWeekends} onClick={()=>setShowWeekends(value=>!value)}>{showWeekends?'隐藏周末':'显示周末'}</button>}{compact&&onHide&&<button className="fde-calendar-hide" type="button" title="隐藏时间轴" aria-label="隐藏时间轴" onClick={onHide}><EyeOff size={17}/></button>}</div></div>
    {view==='personal'&&allowLeader&&<div className="fde-collab-calendar-layer"><strong>个人时间视图</strong><div className="fde-collab-segmented"><button aria-pressed={layer==='personal'} onClick={()=>setLayer('personal')}>我的安排</button><button aria-pressed={layer==='leader'} onClick={()=>setLayer('leader')}>领导时间</button></div></div>}
    {view==='personal'&&layer==='leader'?<FdeLeaderTimePanel initialWeek={week}/>:<section className="fde-collab-card fde-collab-calendar-card"><div className="fde-collab-card-head"><h2>{view==='personal'?userName:'全公司日程'} · {week}—{shiftDate(week,view==='company'||!showWeekends?4:6)}</h2><div className="fde-collab-calendar-actions">{view==='personal'&&<><div className="fde-collab-legend"><span><i/>个人事项</span><span><i data-tone="pending"/>时间冲突</span><span><i data-tone="locked"/>只读事项</span></div><HelpPopover>单击空白时间新建任务；拖动任务可改变时间和日期，拖动底部横条可调整时长。点击任务可编辑或删除。</HelpPopover><Button onClick={()=>open()}><Plus size={16}/>新增任务</Button></>}</div></div>
      {error&&<div role="alert" className="fde-collab-state">{error}<Button variant="secondary" onClick={()=>void reload().catch(e=>setError(e.message))}>重试</Button></div>}{!data&&!error&&<div className="fde-collab-state" role="status">正在读取真实日历来源…</div>}
      {data&&(view==='company'?<FdeCompanyCalendar week={week} items={data.items}/>:<FdeTimeGrid weekStart={week} items={data.items} showWeekends={showWeekends} onCreateAt={createAt} onOpen={key=>{const item=data.items.find(v=>v.key===key);if(item?.editable)open(item);else if(item?.target)navigate(item.target)}} onPropose={proposal=>void applyProposal(proposal)} />)}
    </section>}
    <details className="fde-collab-tools"><summary>日期标记与全部事项</summary><div><Button variant="secondary" onClick={()=>void reload().catch(e=>setError(e.message))}>刷新日历</Button><label><input type="checkbox" checked={includeMilestones} onChange={event=>setIncludeMilestones(event.target.checked)}/>显示已批准节点日期</label></div>
<Card className="p-5"><h3 className="font-semibold">本周事项（含全天、截止点与非工作时段）</h3><div className="mt-3 space-y-3">{data?.items.length===0&&<p className="text-sm text-slate-500">本周暂无可展示的安排。</p>}{data?.items.map(item=><article className="rounded-lg border border-slate-200 p-4" key={item.key}><div className="flex flex-wrap items-center justify-between gap-2"><h4 className="text-sm font-medium">{item.title}</h4><span className="text-xs text-slate-500">{item.ownerName} · {item.editable?(item.source==='task'?'本人任务排期':'本人独立安排'):'只读'}</span></div><p className="mt-2 text-xs text-slate-600">{item.source==='milestone'?timeLocal(new Date(item.startsAt)).slice(0,10):timeLocal(new Date(item.startsAt)).replace('T',' ')}{item.endsAt?` — ${timeLocal(new Date(item.endsAt)).replace('T',' ')}`:item.source==='milestone'?' · 节点日期标记':item.allDay?' · 当日截止':' · 截止点/结束时间未记录'}</p>{item.detail&&<p className="mt-2 whitespace-pre-wrap text-sm text-slate-500">{item.detail}</p>}<div className="mt-3 flex gap-2">{item.editable&&<><Button variant="secondary" disabled={busy} onClick={()=>open(item)}>{item.source==='task'?'编辑任务时间':'编辑安排'}</Button><Button variant="secondary" disabled={busy} onClick={()=>open(item,true)}>{item.source==='task'?'移出时间轴':'取消安排'}</Button></>}{item.target&&<Button variant="secondary" onClick={()=>navigate(item.target!)}>打开来源</Button>}</div></article>)}</div></Card>
    </details>
    <TaskDrawer taskId={selectedTaskId} open={Boolean(selectedTaskId)} onClose={()=>setSelectedTaskId(null)} onAction={(action,task)=>void taskAction(action as UnifiedTaskPrimaryAction,task)}/>
    <Modal open={Boolean(dialog)} title={dialog?.cancel?(dialog.item?.source==='task'&&dialog.item.projectId?'移出日历':'删除个人事项'):dialog?.item?'编辑任务':'新建任务'} onClose={()=>{if(!busy)setDialog(null)}} footer={<>{dialog?.item&&!dialog.cancel&&dialog.item.source==='task'&&<Button variant="secondary" disabled={busy} onClick={()=>{setDialog(null);setSelectedTaskId(dialog.item!.id)}}>查看任务详情</Button>}{dialog?.item&&!dialog.cancel&&<Button variant="secondary" disabled={busy} onClick={()=>open(dialog.item,true)}>{dialog.item.source==='task'&&dialog.item.projectId?'移出日历':'删除'}</Button>}<Button variant="secondary" disabled={busy} onClick={()=>setDialog(null)}>取消</Button><Button loading={busy} disabled={!dialog?.cancel&&!(dialog?.item?.source==='task'?calendarTaskCreateSchema.safeParse({clientRequestId:form.clientRequestId,title:form.title,detail:form.detail,startsAt:form.startsAt,endsAt:form.endsAt}).success:dialog?.item?calendarDefinitionSchema.safeParse(definition).success:calendarTaskCreateSchema.safeParse({clientRequestId:form.clientRequestId,title:form.title,detail:form.detail,startsAt:form.startsAt,endsAt:form.endsAt}).success)} onClick={()=>void submit()}>{dialog?.cancel?(dialog.item?.source==='task'&&dialog.item.projectId?'确认移出':'确认删除'):'保存任务'}</Button></>}>
      <div className="space-y-4">{dialog?.cancel?<div className="fde-calendar-delete-confirm"><strong>{dialog.item?.title}</strong><p>{dialog.item?.source==='task'&&dialog.item.projectId?'任务仍保留在项目任务中，仅从你的日历移除。':'删除后不会再出现在待办和日历中。'}</p></div>:<><label className="block"><span className="label">任务名称</span><input className="input w-full" disabled={dialog?.item?.source==='task'} value={form.title} onChange={e=>field('title',e.target.value)} /></label><label className="block"><span className="label">任务说明</span><textarea className="textarea w-full" disabled={dialog?.item?.source==='task'} value={form.detail} onChange={e=>field('detail',e.target.value)} /></label><div className="fde-calendar-time-fields">{(['startsAt','endsAt'] as const).map((key,i)=><label className="block" key={key}><span className="label">{i?'结束':'开始'}时间</span><input type="datetime-local" step={900} className="input w-full" value={form[key]} onInput={e=>field(key,e.currentTarget.value)} onChange={e=>field(key,e.target.value)} /></label>)}</div>{dialog?.item?.source==='personal'&&<label className="block"><span className="label">可见范围</span><select className="input w-full" value={form.visibility} onChange={e=>field('visibility',e.target.value)}><option value="private">仅本人可见</option><option value="company">公司可见</option></select></label>}</>}</div>
    </Modal>
  </div>
}
