import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { AlertTriangle, CalendarClock, CheckCheck, MessageSquareReply, Plus, RefreshCw, Undo2 } from 'lucide-react'
import { apiGet, apiPost } from '../lib/api'
import { Badge, Button, Card, Modal } from './ui'
import { useToast } from './Toast'
import { weekStartFor } from '../../server/src/contracts/fdeWeeklyPlanContract'
import { timeLocal } from '../../server/src/contracts/fdeTimeContract'
import './fde-workspace.css'

type Schedule = { id: string; preferredStart: string; alternativeStart: string | null; scheduledStart: string | null; durationMinutes: number; location: string; status: string }
type Directive = { id: string; issuerName: string; issuerId: string; content: string; conversion: 'action' | 'pending' | 'leadership'; requiresReceipt: boolean; version: number; acknowledgedAt: string | null; withdrawnAt: string | null; withdrawalReason: string | null; status: string; task: { id: string; owner: string; ownerUserId: string; dueDate: string; dueTime: string | null; status: string; progress: number; version: number }; schedules: Schedule[]; events: Array<{ id: string; action: string; actorId: string; reason: string; version: number; createdAt: string }>; capabilities: { canAcknowledge: boolean; canWithdraw: boolean } }
type Data = { canCreate: boolean; members: Array<{ id: string; name: string }>; notices: Array<{ id: string; directiveId: string; kind: string; readAt: string | null }>; list: Directive[] }
type Dialog = { mode: 'create' } | { mode: 'acknowledge' | 'withdraw'; directive: Directive }
const labels = { action: '项目行动', pending: '待确认事项', leadership: '领导日程' }
const scheduleLabels: Record<string,string> = {draft:'草稿待补充',requested:'已申请',pending:'待领导确认',supplement:'需补信息',confirmed:'已确认',rejected:'已拒绝',withdrawn:'已撤回',cancelled:'已取消'}
const eventLabels: Record<string, string> = {
  publish: '发布批示', acknowledge: '执行人回执', withdraw: '撤回批示',
  progress: '执行反馈', submission: '提交成果', accept: '验收通过', return: '成果退回',
  'extension-request': '申请延期', 'extension-approve': '延期通过', 'extension-reject': '延期拒绝',
  'extension-return': '延期退回', 'extension-resubmit': '延期重提', 'extension-withdraw': '延期撤回',
  'project-close': '项目关闭联动',
}
function tomorrowAtSix() { const now = new Date(Date.now() + 86400000 + 8 * 3600000).toISOString().slice(0, 10); return `${now}T18:00` }
function formatDate(value: string) { return new Date(value).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai', hour12: false }) }

export function FdeDirectivePanel({ projectId, onChanged, compact = false }: { projectId: string; onChanged: () => Promise<void>; compact?: boolean }) {
  const navigate = useNavigate()
  const { showToast } = useToast(), [data, setData] = useState<Data | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [dialog, setDialog] = useState<Dialog | null>(null)
  const [form, setForm] = useState({ requestId: '', content: '', ownerUserId: '', dueAt: tomorrowAtSix(), conversion: 'action' as Directive['conversion'], requiresReceipt: true, reason: '' })
  const endpoint = `/projects/${projectId}/directives`
  const reload = async () => { const next = await apiGet<Data>(endpoint); setData(next); setError('') }
  useEffect(() => { let cancelled = false; setData(null); void apiGet<Data>(endpoint).then((next) => { if (!cancelled) { setData(next); setError('') } }).catch((cause) => { if (!cancelled) setError((cause as Error).message) }); return () => { cancelled = true } }, [endpoint])
  const open = (next: Dialog) => { setForm({ requestId: crypto.randomUUID(), content: '', ownerUserId: data?.members[0]?.id ?? '', dueAt: tomorrowAtSix(), conversion: 'action', requiresReceipt: true, reason: '' }); setDialog(next) }
  const run = async (operation: () => Promise<unknown>, success: string) => { setBusy(true); try { await operation(); await reload(); setDialog(null); showToast(success); await onChanged().catch(() => {}) } catch (cause) { showToast((cause as Error).message, 'error'); await reload().catch(() => {}) } finally { setBusy(false) } }
  const submit = () => {
    if (!dialog) return
    if (dialog.mode === 'create') void run(() => apiPost(endpoint, { clientRequestId: form.requestId, content: form.content, ownerUserId: form.ownerUserId, dueAt: form.dueAt, conversion: form.conversion, requiresReceipt: form.requiresReceipt }), '批示已发布，并生成唯一执行任务')
    else void run(() => apiPost(`${endpoint}/${dialog.directive.id}/actions`, { clientRequestId: form.requestId, expectedVersion: dialog.directive.version, action: dialog.mode, reason: form.reason }), dialog.mode === 'withdraw' ? '批示已撤回，未结束派生项已关闭' : '回执已保存')
  }
  if (error) return <Card className="p-5"><p className="text-sm text-red-600">批示加载失败：{error}</p><Button variant="secondary" onClick={() => void reload().catch((cause) => showToast((cause as Error).message, 'error'))}>重试</Button></Card>
  if (!data) return <Card className="p-5 text-sm text-slate-500">正在读取领导批示与执行关联…</Card>
  const validCreate = Boolean(form.content.trim().length >= 2 && form.ownerUserId && form.dueAt)
  const validAction = form.reason.trim().length >= (dialog?.mode === 'withdraw' ? 5 : 2)
  return <div className={`fde-workspace ${compact ? 'fde-detail-directives' : ''}`}><Card className="fde-panel p-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">{compact ? '领导事项' : '领导批示'}</h2><p className="mt-1 text-xs text-slate-500">批示与唯一项目任务联动；成果仍在项目待办提交并异人验收。撤回只能由发出者执行。</p></div><div className="flex gap-2"><Button variant="secondary" disabled={busy} onClick={() => void reload().catch((cause) => showToast((cause as Error).message, 'error'))}><RefreshCw className="h-4 w-4" />刷新</Button>{data.canCreate && <Button onClick={() => open({ mode: 'create' })}><Plus className="h-4 w-4" />发布批示</Button>}</div></div>
    {data.notices.length > 0 && <div className="mt-4 rounded-lg bg-amber-50 p-3 text-xs text-amber-900"><AlertTriangle className="mr-1 inline h-4 w-4" />有 {data.notices.length} 条批示动态；打开对应批示可查看完整历史。</div>}
    <div className="mt-4 space-y-3">{!data.list.length && <p className="rounded-lg bg-slate-50 p-5 text-sm text-slate-500">暂无您有权查看的批示。</p>}{data.list.map((item) => <section className="rounded-xl border border-slate-200 p-4" key={item.id}>
      <div className="flex flex-wrap items-start justify-between gap-3"><div className="max-w-3xl"><div className="mb-2 flex flex-wrap gap-2"><Badge tone="slate">{labels[item.conversion]}</Badge><Badge tone={item.status === '已落实' ? 'green' : item.withdrawnAt ? 'slate' : 'amber'}>{item.status}</Badge>{item.requiresReceipt && <Badge tone="blue">要求回执</Badge>}</div><h3 className="whitespace-pre-wrap text-sm font-semibold">{item.content}</h3><p className="mt-2 text-xs text-slate-500">{item.issuerName} 发出 · {item.task.owner} 执行 · 截止 {item.task.dueDate} {item.task.dueTime ?? '当日结束'}</p></div><span className="text-xs text-slate-400">批示 v{item.version} / 任务 v{item.task.version}</span></div>
      <div className="mt-3 rounded-lg bg-slate-50 p-3 text-xs text-slate-600">关联任务：{item.task.status} · {item.task.progress}% · ID {item.task.id}</div>
      {item.schedules.map((schedule) => <div key={schedule.id} className="mt-3 rounded-lg bg-[#e6f0ef] p-3 text-xs text-[#214b54]"><CalendarClock className="mr-1 inline h-4 w-4" />领导时间需求：首选 {formatDate(schedule.preferredStart)}，备选 {schedule.alternativeStart ? formatDate(schedule.alternativeStart) : '未填写'}；当前排期 {schedule.scheduledStart ? formatDate(schedule.scheduledStart) : '尚未排期'}，{schedule.durationMinutes} 分钟 · {scheduleLabels[schedule.status]??schedule.status}<Button variant="secondary" className="ml-2" onClick={()=>navigate(`/collaboration?view=time&week=${weekStartFor(timeLocal(new Date(schedule.scheduledStart??schedule.preferredStart)).slice(0,10))}&request=${schedule.id}`)}>处理时间需求</Button></div>)}
      <div className="mt-3 flex flex-wrap gap-2">{item.capabilities.canAcknowledge && <Button variant="secondary" disabled={busy} onClick={() => open({ mode: 'acknowledge', directive: item })}><MessageSquareReply className="h-4 w-4" />{item.conversion === 'pending' ? '确认接办' : '提交回执'}</Button>}{item.capabilities.canWithdraw && <Button variant="secondary" disabled={busy} onClick={() => open({ mode: 'withdraw', directive: item })}><Undo2 className="h-4 w-4" />撤回批示</Button>}<Button variant="secondary" onClick={() => navigate(`/projects/${projectId}?tab=tasks`)}><CheckCheck className="h-4 w-4" />进入成果反馈与验收</Button>{data.notices.filter((notice) => notice.directiveId === item.id && !notice.readAt).map((notice) => <Button key={notice.id} variant="secondary" disabled={busy} onClick={() => void run(() => apiPost(`/projects/${projectId}/directive-notices/${notice.id}/read`, {}), '通知已读')}>标记已读</Button>)}</div>
      {item.events.length > 0 && <details className="mt-3 border-t border-slate-100 pt-3"><summary className="cursor-pointer text-xs text-slate-500">批示版本与联动历史</summary><div className="mt-2 space-y-2">{item.events.map((event) => <p className="text-xs text-slate-500" key={event.id}>v{event.version} · {eventLabels[event.action] ?? event.action} · {formatDate(event.createdAt)}{event.reason ? ` · ${event.reason}` : ''}</p>)}</div></details>}
    </section>)}</div>
  </Card><Modal open={Boolean(dialog)} title={dialog?.mode === 'create' ? '发布领导批示' : dialog?.mode === 'withdraw' ? '撤回领导批示' : '提交批示回执'} onClose={() => { if (!busy) setDialog(null) }} footer={<><Button variant="secondary" disabled={busy} onClick={() => setDialog(null)}>取消</Button><Button loading={busy} disabled={dialog?.mode === 'create' ? !validCreate : !validAction} onClick={submit}>确认提交</Button></>}><div className="space-y-4">
    {dialog?.mode === 'create' ? <><label className="block"><span className="label">批示内容</span><textarea className="textarea min-h-24 w-full" maxLength={300} value={form.content} onChange={(e) => setForm({ ...form, content: e.target.value, requestId: crypto.randomUUID() })} /></label><label className="block"><span className="label">执行人</span><select className="input w-full" value={form.ownerUserId} onChange={(e) => setForm({ ...form, ownerUserId: e.target.value, requestId: crypto.randomUUID() })}>{data.members.map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select></label><label className="block"><span className="label">精确截止时间（上海时间）</span><input className="input w-full" type="datetime-local" value={form.dueAt} onInput={(e) => { const dueAt = e.currentTarget.value; setForm((previous) => ({ ...previous, dueAt, requestId: crypto.randomUUID() })) }} onChange={(e) => { const dueAt = e.target.value; setForm((previous) => ({ ...previous, dueAt, requestId: crypto.randomUUID() })) }} /></label><label className="block"><span className="label">转换方式</span><select className="input w-full" value={form.conversion} onChange={(e) => setForm({ ...form, conversion: e.target.value as Directive['conversion'], requestId: crypto.randomUUID() })}><option value="action">项目行动</option><option value="pending">待确认事项</option><option value="leadership">领导日程</option></select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.requiresReceipt} onChange={(e) => setForm({ ...form, requiresReceipt: e.target.checked, requestId: crypto.randomUUID() })} />要求执行人回执</label>{form.conversion === 'leadership' && <p className="rounded-lg bg-amber-50 p-3 text-xs text-amber-900">将生成待确认的领导时间申请草案，不代表已排期或已由领导确认。</p>}</> : <label className="block"><span className="label">{dialog?.mode === 'withdraw' ? '撤回原因' : '回执说明'}</span><textarea className="textarea min-h-24 w-full" value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value, requestId: crypto.randomUUID() })} /></label>}
  </div></Modal></div>
}
