import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { apiGet } from '../lib/api'
import { Button, Card } from './ui'

type Inbox = { list: Array<{ id: string; submissionId: string; projectId: string; title: string; kind: string; readAt: string | null }>; total: number; pageSize: number }
export function FdeMaterialInbox() {
  const navigate = useNavigate(), [data, setData] = useState<Inbox | null>(null), [error, setError] = useState(''), [page, setPage] = useState(1), [refresh, setRefresh] = useState(0)
  useEffect(() => { const reload = () => setRefresh(n => n + 1); window.addEventListener('focus', reload); return () => window.removeEventListener('focus', reload) }, [])
  useEffect(() => { let cancelled = false; setData(null); setError(''); void apiGet<Inbox>(`/projects/material-inbox?page=${page}&pageSize=5`).then(value => { if (!cancelled) setData(value) }).catch(cause => { if (!cancelled) setError((cause as Error).message) }); return () => { cancelled = true } }, [page, refresh])
  return <Card className="mb-5 overflow-hidden"><div className="flex items-center justify-between gap-3 border-b border-slate-100 p-4"><div><h2 className="font-semibold">材料送审与反馈</h2><p className="mt-1 text-xs text-slate-400">站内通知 · 打开材料后逐人处理，不代替阶段审批</p></div><Button variant="secondary" onClick={() => setRefresh(n => n + 1)}>刷新材料通知</Button></div>{error ? <p role="alert" className="p-4 text-sm text-red-600">{error}</p> : !data ? <p className="p-4 text-sm text-slate-400">正在读取材料通知…</p> : <><div className="divide-y divide-slate-100">{data.list.map(item => <button key={item.id} className="flex w-full items-center justify-between gap-3 p-4 text-left text-sm hover:bg-slate-50" onClick={() => navigate(`/projects/${item.projectId}?tab=files&material=${item.submissionId}`)}><span className="break-all">{item.title}</span><span className="shrink-0 text-xs text-[#315f68]">{item.kind === 'feedback' ? '收到反馈' : item.readAt ? '已读待批复' : '待阅读批复'}</span></button>)}</div>{!data.total && <p className="p-4 text-sm text-slate-400">暂无当前有权处理的材料通知。</p>}<div className="flex items-center justify-between gap-2 border-t border-slate-100 p-3 text-xs text-slate-400"><span>共 {data.total} 条 · 第 {page} 页</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage(n => n - 1)}>上页通知</button><button disabled={page * data.pageSize >= data.total} onClick={() => setPage(n => n + 1)}>下页通知</button></div></div></>}</Card>
}
