import { useEffect, useRef, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { FDE_PROJECT_DUTIES } from '../../server/src/contracts/fdeGovernanceContract'
import { FDE_NON_INVESTMENT_TYPES, typePolicyCode, typePolicyCommand, typePolicyDefinition, type TypePolicyCommand, type TypePolicyDefinition } from '../../server/src/contracts/fdeTypePolicyContract'
import { typePolicyDetailView, typePolicyListView, type TypePolicyDetailView, type TypePolicyListView, type TypePolicyVersionView } from '../../server/src/contracts/fdeTypePolicyViewContract'
import { apiGet, apiPost } from '../lib/api'
import { forgetTypePolicyPending, markerForTypePolicy, readTypePolicyPending, rememberTypePolicyPending, typePolicyPendingKey, validateTypePolicyReceipt, validateTypePolicyRecovery, type TypePolicyPending } from '../lib/fdeTypePolicyRecovery'
import { addTypeDraftAction, addTypeDraftStage, moveTypeDraftAction, moveTypeDraftStage, nextTypeDraftKey, reassignTypeDraftAction } from '../lib/fdeTypePolicyEditor'
import { useAuthStore } from '../store/useAuthStore'
import { Badge, Button, Card, Modal } from './ui'
import './fde-workspace.css'

const root = '/fde-type-policies', names = { draft: '草稿', approved: '已独立审核', published: '已发布' }
const duties = [{ code: 'owner', label: '项目负责人' }, ...FDE_PROJECT_DUTIES]
const labels = { create: '新建草稿', save: '保存草稿', approve: '独立审核', publish: '发布版本', activate: '启用新登记', deactivate: '停用新登记' }
const explain = (e: unknown) => e && typeof e === 'object' && 'issues' in e ? (e.issues as Array<{ message: string }>).map(i => i.message).join('；') : (e as Error).message
const stage = (i: number): TypePolicyDefinition['stages'][number] => ({ key: `stage_${i}`, name: '', outcome: '', allowWaiver: false, materials: [], approvals: [{ duty: 'owner', name: '负责人核对成果', mode: '会签' }] })
const action = (i: number, stageKey: string): TypePolicyDefinition['actions'][number] => ({ key: `action_${i}`, stageKey, title: '', duty: 'owner', deliverable: '', position: 100, needLeader: false })
const blank = (): TypePolicyDefinition => ({ schemaVersion: 2, type: 'fundraising', timezone: 'Asia/Shanghai', cycleDays: [15], calendar: { basis: 'calendar', workingWeekdays: [], holidays: [], extraWorkingDates: [] }, stages: [stage(1), stage(2)], actions: [{ ...action(1, 'stage_1'), position: 50 }, action(2, 'stage_2')] })
type Editor = { version: TypePolicyVersionView | null; clone: boolean }

export function FdeTypePolicyEntry() {
  const uid = useAuthStore(s => s.user?.id ?? ''), [allowed, setAllowed] = useState(false)
  useEffect(() => { let active = true; setAllowed(false); void apiGet<unknown>(root).then(v => { if (active && useAuthStore.getState().user?.id === uid) setAllowed(Boolean(typePolicyListView.parse(v).capabilities)) }).catch(() => {}); return () => { active = false } }, [uid])
  return allowed ? <Link className="mb-4 inline-block text-sm text-brand-700 underline" to="/workflow?view=type-policies">非投资流程模板 · 独立审核</Link> : null
}
export function FdeTypePolicyPanel() { const uid = useAuthStore(s => s.user?.id ?? ''); return <AccountPanel key={uid} uid={uid} /> }
function AccountPanel({ uid }: { uid: string }) {
  const [params, setParams] = useSearchParams(), selectedId = params.get('typePolicy') ?? ''
  const [page, setPage] = useState(1), [eventPage, setEventPage] = useState(1), [reload, setReload] = useState(0)
  const [list, setList] = useState<TypePolicyListView | null>(null), [detail, setDetail] = useState<TypePolicyDetailView | null>(null), [error, setError] = useState(''), [notice, setNotice] = useState('')
  const [editor, setEditor] = useState<Editor | null>(null), [config, setConfig] = useState<TypePolicyDefinition>(blank), [reason, setReason] = useState(''), [ack, setAck] = useState(false)
  const [targetDate, setTargetDate] = useState(''), [cycle, setCycle] = useState(15), [preview, setPreview] = useState<Array<{ key: string; title: string; dueDate: string }> | null>(null)
  const [holidayText, setHolidayText] = useState(''), [extraWorkingText, setExtraWorkingText] = useState('')
  const [registrationRoles, setRegistrationRoles] = useState<Array<{ id: string; name: string }>>([])
  const [pending, setPending] = useState<TypePolicyPending | null>(null), [storageError, setStorageError] = useState(''), [ready, setReady] = useState(false), [busy, setBusy] = useState(false)
  const mounted = useRef(true), writing = useRef(false), sequence = useRef(0), key = typePolicyPendingKey(uid)
  const current = () => mounted.current && (useAuthStore.getState().user?.id ?? '') === uid
  const blocked = busy || !ready || Boolean(pending) || Boolean(storageError)
  const recoverMarker = () => { try { setPending(readTypePolicyPending(sessionStorage, key)); setReady(true); setStorageError('') } catch { setStorageError('浏览器恢复标识不可读，已阻止写入。请恢复存储后核对，不要删除未知请求。'); setReady(false) } }
  useEffect(() => { let active = true; void apiGet<{ roles: Array<{ id: string; name: string }> }>(`${root}/registration-roles`).then(v => { if (active && current()) setRegistrationRoles(v.roles) }).catch(() => { if (active) setRegistrationRoles([]) }); return () => { active = false } }, [reload])
  useEffect(() => { mounted.current = true; recoverMarker(); const focus = () => { if (!writing.current) { recoverMarker(); setReload(n => n + 1) } }; window.addEventListener('focus', focus); return () => { mounted.current = false; sequence.current++; window.removeEventListener('focus', focus) } }, [])
  useEffect(() => {
    const seq = ++sequence.current; setList(null); setDetail(null); setEditor(null); setError('')
    void Promise.all([apiGet<unknown>(root), selectedId ? apiGet<unknown>(`${root}/${selectedId}?page=${page}&eventPage=${eventPage}`) : Promise.resolve(null)]).then(([l, d]) => {
      const parsedList = typePolicyListView.parse(l), parsedDetail = d === null ? null : typePolicyDetailView.parse(d)
      if (current() && seq === sequence.current) { setList(parsedList); setDetail(parsedDetail) }
    }).catch(e => { if (current() && seq === sequence.current) setError(explain(e)) })
    return () => { sequence.current++ }
  }, [selectedId, page, eventPage, reload])
  const choose = (id: string) => { const next = new URLSearchParams(params); next.set('typePolicy', id); setPage(1); setEventPage(1); setParams(next) }
  const open = (v: TypePolicyVersionView | null, clone = false) => { setEditor({ version: v, clone }); setConfig(v ? structuredClone(v.configuration) : blank()); setHolidayText(v?.configuration.calendar.holidays.join(' ') ?? ''); setExtraWorkingText(v?.configuration.calendar.extraWorkingDates.join(' ') ?? ''); setReason(''); setAck(false); setPreview(null); setTargetDate(''); setCycle(v?.configuration.cycleDays[0] ?? 15); setError('') }
  const editable = Boolean(list?.capabilities.manage && (!editor?.version || editor.clone || editor.version.capabilities.save))
  const unsaved = Boolean(editor?.version && !editor.clone && JSON.stringify(config) !== JSON.stringify(editor.version.configuration))
  const change = (next: TypePolicyDefinition) => { setConfig(next); setAck(false); setPreview(null) }
  const finish = (marker: TypePolicyPending, message: string, policyId?: string) => {
    if (!current()) return
    forgetTypePolicyPending(sessionStorage, key, marker); setPending(null); setError(''); setNotice(message); setEditor(null)
    if (policyId) choose(policyId); setReload(n => n + 1)
  }
  const execute = async (kind: TypePolicyCommand['action']) => {
    if (blocked || writing.current || !editor || !list || !ack) return
    let command: TypePolicyCommand
    try {
      command = typePolicyCommand.parse(kind === 'create' ? { action: kind, commandId: crypto.randomUUID(), configuration: config, expectedPolicyVersion: list.policies.find(p => p.code === typePolicyCode(config.type))?.version ?? 0, reason }
        : { action: kind, commandId: crypto.randomUUID(), policyId: editor.version!.policyId, versionId: editor.version!.id, expectedVersion: editor.version!.version, reason,
          ...(kind === 'save' ? { configuration: config } : {}), ...(['publish', 'activate', 'deactivate'].includes(kind) ? { expectedPolicyVersion: detail!.policy.version } : {}) })
      if (['approve', 'publish', 'activate', 'deactivate'].includes(kind) && unsaved) throw new Error('存在未保存修改，不能办理另一份内容')
    } catch (e) { setError(explain(e)); return }
    const marker = markerForTypePolicy(command)
    try { rememberTypePolicyPending(sessionStorage, key, marker); setPending(marker) } catch (e) { setStorageError(explain(e)); return }
    writing.current = true; setBusy(true)
    try { const receipt = validateTypePolicyReceipt(await apiPost<unknown>(`${root}/commands`, command), marker); finish(marker, `${labels[kind]}已完成；${kind === 'activate' ? '仅明确授权角色可登记此版项目。' : kind === 'deactivate' ? '停止新登记，既有项目按已批准规则保留绑定版本。' : '未自动启用登记或迁移现有项目。'}`, receipt.policyId) }
    catch (e) { if (current()) { setError(`${explain(e)}；请先核对原请求结果，不要重复提交。`); recoverMarker() } }
    finally { writing.current = false; if (current()) setBusy(false) }
  }
  const recover = async () => {
    if (!pending || writing.current) return; const marker = pending; writing.current = true; setBusy(true)
    try { const result = validateTypePolicyRecovery(await apiPost<unknown>(`${root}/commands/recover`, { commandId: marker.commandId }), marker); finish(marker, result.state === 'committed' ? '已找回原操作回执，没有重复执行。' : '原操作未提交，已封闭旧请求；请重新读取后确认。', result.receipt?.policyId) }
    catch (e) { if (current()) setError(explain(e)) } finally { writing.current = false; if (current()) setBusy(false) }
  }
  const previewPlan = async () => {
    if (writing.current) return; setError(''); setPreview(null); setBusy(true); writing.current = true
    try {
      const result = await apiPost<{ actions: Array<{ key: string; title: string; dueDate: string }>; persisted: boolean }>(`${root}/preview`, { configuration: typePolicyDefinition.parse(config), cycleDays: cycle, targetDate })
      if (!Array.isArray(result.actions) || result.persisted !== false) throw new Error('预览回执不完整')
      if (current()) setPreview(result.actions)
    } catch (e) { if (current()) setError(explain(e)) } finally { writing.current = false; if (current()) setBusy(false) }
  }
  const updateStage = (i: number, patch: Partial<TypePolicyDefinition['stages'][number]>) => change({ ...config, stages: config.stages.map((s, n) => n === i ? { ...s, ...patch } : s) })
  const updateAction = (i: number, patch: Partial<TypePolicyDefinition['actions'][number]>) => change({ ...config, actions: config.actions.map((a, n) => n === i ? { ...a, ...patch } : a) })
  return <div className="fde-workspace space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-semibold">非投资流程模板</h1><p className="mt-2 text-xs leading-6 text-slate-500">独立定义阶段、成果、材料和职责。目录及正式规则待业务确认；发布不等于启用。投资模板、AI 与线索模板不在此修改。</p></div><Button variant="secondary" disabled={busy} onClick={() => { recoverMarker(); setReload(n => n + 1) }}>刷新模板</Button></div>
    <Card className="border-amber-200 bg-amber-50 p-4 text-sm">发布不等于启用。登记角色、分类及在途规则须随模板独立审核，再显式启用。未配置规则时拒绝登记；不自动转换线索或改写在途流程。</Card>
    {notice && <p role="status" className="text-sm text-emerald-700">{notice}</p>}{(error || storageError) && <p role="alert" className="break-words text-sm text-red-700">{error || storageError}</p>}
    {pending && <Card className="p-4"><p className="mb-3 text-sm">有一笔“{labels[pending.action]}”尚待核对，新的写入已暂停。</p><Button disabled={busy} onClick={() => void recover()}>核对原请求结果</Button></Card>}
    {list && <div className="flex flex-wrap gap-2">{list.policies.map(p => <Button key={p.id} variant="secondary" disabled={busy} onClick={() => choose(p.id)}>{p.name}</Button>)}{list.capabilities.manage && <Button disabled={blocked} onClick={() => open(null)}>编制新模板版本</Button>}{!list.policies.length && <span className="text-sm text-slate-500">暂无已保存的非投资模板；系统不会导入演示规则。</span>}</div>}
    {detail && <Card className="p-5"><h2 className="font-semibold">{detail.policy.name}</h2><p className="my-2 text-xs text-slate-500">已发布版本 {detail.versions.find(v => v.id === detail.policy.activeVersionId)?.revision ?? (detail.policy.activeVersionId ? '见历史页' : '—')} · 绑定项目 {detail.boundProjects} · {detail.policy.enabled ? '当前版本已启用' : '当前版本未启用'}</p>
      {detail.versions.map(v => <div key={v.id} className="mb-3 flex flex-wrap items-center gap-3 rounded-xl border p-4"><div className="min-w-0 flex-1"><p>V{v.revision} <Badge tone={v.status === 'draft' ? 'amber' : 'green'}>{names[v.status]}</Badge></p><p className="mt-2 break-words text-xs text-slate-500">{v.reason} · 编制 {v.createdByName} · 审核 {v.approvedByName ?? '待审核'}</p></div><Button variant="secondary" disabled={busy} onClick={() => open(v)}>查看 / 办理</Button>{detail.capabilities.manage && <Button variant="secondary" disabled={blocked} onClick={() => open(v, true)}>基于此版修订</Button>}</div>)}
      <div className="flex gap-3"><Button variant="secondary" disabled={busy || page === 1} onClick={() => setPage(n => n - 1)}>上一页版本</Button><span>第 {page} 页</span><Button variant="secondary" disabled={busy || !detail.hasMore} onClick={() => setPage(n => n + 1)}>下一页版本</Button></div>
      <h3 className="mb-2 mt-5 text-sm font-semibold">操作历史</h3>{detail.events.map(e => <p key={e.id} className="mb-2 break-words text-xs text-slate-500">{labels[e.action]} · {e.reason}</p>)}<div className="mt-3 flex gap-3"><Button variant="secondary" disabled={busy || eventPage === 1} onClick={() => setEventPage(n => n - 1)}>上一页历史</Button><Button variant="secondary" disabled={busy || !detail.eventsHaveMore} onClick={() => setEventPage(n => n + 1)}>下一页历史</Button></div>
    </Card>}
    <Modal open={Boolean(editor)} onClose={() => { if (!busy) setEditor(null) }} title={`非投资流程模板${editor?.version ? ` V${editor.version.revision}` : ''}${editor?.clone ? ' · 新修订' : ''}`} width="max-w-6xl" footer={<><Button variant="secondary" disabled={busy} onClick={() => setEditor(null)}>关闭</Button>{editable && <Button disabled={blocked || !ack || reason.trim().length < 5} onClick={() => void execute(!editor?.version || editor.clone ? 'create' : 'save')}>确认保存草稿</Button>}{editor?.version?.capabilities.approve && !editor.clone && <Button disabled={blocked || !ack || unsaved || reason.trim().length < 5} onClick={() => void execute('approve')}>确认独立审核</Button>}{editor?.version?.capabilities.publish && !editor.clone && <Button disabled={blocked || !ack || unsaved || reason.trim().length < 5} onClick={() => void execute('publish')}>确认发布版本</Button>}{editor?.version?.capabilities.activate && !editor.clone && <Button disabled={blocked || !ack || unsaved || reason.trim().length < 5} onClick={() => void execute('activate')}>确认启用新登记</Button>}{editor?.version?.capabilities.deactivate && !editor.clone && <Button variant="secondary" disabled={blocked || !ack || unsaved || reason.trim().length < 5} onClick={() => void execute('deactivate')}>确认停用新登记</Button>}</>}>
      {editor && <div className="space-y-5">
        {(error || storageError) && <p role="alert" className="text-sm text-red-700">{error || storageError}</p>}
        <fieldset disabled={!editable || busy} className="space-y-5">
          <section className="space-y-3 rounded-xl border p-4"><label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={Boolean(config.registration)} onChange={e => change({ ...config, registration: e.target.checked ? { roleIds: [], classification: '' as 'normal', ownership: 'registrar', onDisable: 'continue_bound_version', ruleReference: '' } : undefined })} />配置需独立审核的登记规则（不默认授权）</label>
            {config.registration && <><p className="text-xs text-slate-600">本入口仅支持登记人担任负责人、停用后既有项目继续绑定版本。若业务选择代登记或冻结在途项目，请勿启用此配置，需另行明确规则。</p><div className="flex flex-wrap gap-3">{registrationRoles.map(role => <label key={role.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={config.registration!.roleIds.includes(role.id)} onChange={e => change({ ...config, registration: { ...config.registration!, roleIds: e.target.checked ? [...config.registration!.roleIds, role.id] : config.registration!.roleIds.filter(id => id !== role.id) } })} />{role.name}</label>)}</div>{!registrationRoles.length && <p role="alert" className="text-sm text-amber-700">登记角色尚未加载或无有效候选；不能凭名称授予权限。</p>}<label className="block text-sm">登记后分类<select className="input w-full" value={config.registration.classification} onChange={e => change({ ...config, registration: { ...config.registration!, classification: e.target.value as 'normal' | 'key' } })}><option value="">请明确选择分类</option><option value="normal">普通项目</option><option value="key">重点项目</option></select></label><label className="block text-sm">登记授权与在途处理规则依据<textarea className="input min-h-20 w-full" value={config.registration.ruleReference} onChange={e => change({ ...config, registration: { ...config.registration!, ruleReference: e.target.value } })} /></label></>}
          </section>
          <label className="block"><span className="label">项目类型（候选目录，正式范围待确认）</span><select className="input w-full" disabled={Boolean(editor.version) && !editor.clone} value={config.type} onChange={e => change({ ...config, type: e.target.value as TypePolicyDefinition['type'] })}>{FDE_NON_INVESTMENT_TYPES.map(t => <option key={t.code} value={t.code}>{t.name}</option>)}</select></label>
          <section className="space-y-3 rounded-xl border p-4"><h3 className="font-semibold">执行计划审核规则</h3><p className="text-xs text-slate-500">与阶段成果审核分别配置。旧版本未配置时仍可查看，但不能启动执行；新增规则须另建修订、独立审核并发布，不改历史。</p>{config.planApprovals?.map((n, i) => <div key={i} className="grid gap-3 sm:grid-cols-3"><select aria-label={`计划审核职责${i + 1}`} className="input" value={n.duty} onChange={e => change({ ...config, planApprovals: config.planApprovals!.map((v, j) => i === j ? { ...v, duty: e.target.value as typeof n.duty } : v) })}>{duties.map(d => <option key={d.code} value={d.code}>{d.label}</option>)}</select><input aria-label={`计划审核名称${i + 1}`} className="input" value={n.name} onChange={e => change({ ...config, planApprovals: config.planApprovals!.map((v, j) => i === j ? { ...v, name: e.target.value } : v) })} /><select aria-label={`计划审核方式${i + 1}`} className="input" value={n.mode} onChange={e => change({ ...config, planApprovals: config.planApprovals!.map((v, j) => i === j ? { ...v, mode: e.target.value as typeof n.mode } : v) })}><option>会签</option><option>或签</option></select></div>)}<div className="flex gap-2"><Button variant="secondary" disabled={(config.planApprovals?.length ?? 0) >= 12} onClick={() => change({ ...config, planApprovals: [...(config.planApprovals ?? []), { duty: 'concerned_leader', name: '计划审核', mode: '会签' }] })}>增加计划审核节点</Button>{config.planApprovals?.length && <Button variant="secondary" onClick={() => { const next = { ...config }; if (next.planApprovals!.length === 1) delete next.planApprovals; else next.planApprovals = next.planApprovals!.slice(0, -1); change(next) }}>移除末尾计划审核节点</Button>}</div></section>
          <div><span className="label">允许周期</span><div className="flex flex-wrap gap-4">{([15, 30, 40, 50] as const).map(d => <label key={d}><input type="checkbox" checked={config.cycleDays.includes(d)} onChange={() => change({ ...config, cycleDays: config.cycleDays.includes(d) ? config.cycleDays.filter(n => n !== d) : [...config.cycleDays, d].sort((a, b) => a - b) })} /> {d} 天</label>)}</div></div>
          <label className="block"><span className="label">日期口径</span><select className="input w-full" value={config.calendar.basis} onChange={e => { setHolidayText(''); setExtraWorkingText(''); change({ ...config, calendar: { basis: e.target.value as 'calendar' | 'working', workingWeekdays: [], holidays: [], extraWorkingDates: [] } }) }}><option value="calendar">自然日</option><option value="working">明确配置的工作日</option></select></label>
          {config.calendar.basis === 'working' && <div className="space-y-3"><div className="flex flex-wrap gap-3">{['日', '一', '二', '三', '四', '五', '六'].map((d, i) => <label key={i}><input type="checkbox" checked={config.calendar.workingWeekdays.includes(i)} onChange={() => change({ ...config, calendar: { ...config.calendar, workingWeekdays: config.calendar.workingWeekdays.includes(i) ? config.calendar.workingWeekdays.filter(n => n !== i) : [...config.calendar.workingWeekdays, i] } })} />周{d}</label>)}</div>{(['holidays', 'extraWorkingDates'] as const).map(k => <label key={k} className="block"><span className="label">{k === 'holidays' ? '休息日期' : '补班日期'}（YYYY-MM-DD，空格分隔）</span><textarea className="textarea w-full" value={k === 'holidays' ? holidayText : extraWorkingText} onChange={e => { (k === 'holidays' ? setHolidayText : setExtraWorkingText)(e.target.value); change({ ...config, calendar: { ...config.calendar, [k]: e.target.value.split(/\s+/).filter(Boolean) } }) }} /></label>)}</div>}
          <section><h3 className="mb-3 font-semibold">阶段与成果门禁</h3>{config.stages.map((s, i) => <div className="mb-4 space-y-3 rounded-xl border p-4" key={i}><div className="grid gap-3 sm:grid-cols-2"><label><span className="label">阶段编号 {i + 1}</span><input className="input w-full" value={s.key} onChange={e => { const newKey = e.target.value; change({ ...config, stages: config.stages.map((r, n) => n === i ? { ...r, key: newKey } : r), actions: config.actions.map(a => a.stageKey === s.key ? { ...a, stageKey: newKey } : a) }) }} /></label><label><span className="label">阶段名称 {i + 1}</span><input className="input w-full" value={s.name} onChange={e => updateStage(i, { name: e.target.value })} /></label></div><label className="block"><span className="label">阶段验收成果 {i + 1}</span><textarea className="textarea w-full" value={s.outcome} onChange={e => updateStage(i, { outcome: e.target.value })} /></label><label><input type="checkbox" checked={s.allowWaiver} onChange={e => updateStage(i, { allowWaiver: e.target.checked })} />允许按批准权限说明材料免传理由</label>
            {s.materials.map((m, j) => <div className="flex flex-wrap gap-2" key={j}><input className="input min-w-0 flex-1" aria-label={`阶段${i + 1}材料编号${j + 1}`} value={m.key} onChange={e => updateStage(i, { materials: s.materials.map((r, n) => n === j ? { ...r, key: e.target.value } : r) })} /><input className="input min-w-0 flex-1" aria-label={`阶段${i + 1}材料名称${j + 1}`} value={m.label} onChange={e => updateStage(i, { materials: s.materials.map((r, n) => n === j ? { ...r, label: e.target.value } : r) })} /><Button variant="secondary" onClick={() => updateStage(i, { materials: s.materials.filter((_, n) => n !== j) })}>移除材料</Button></div>)}<Button variant="secondary" disabled={s.materials.length >= 30} onClick={() => updateStage(i, { materials: [...s.materials, { key: nextTypeDraftKey('material', s.materials.map(m => m.key)), label: '' }] })}>增加材料要求</Button>
            <p className="text-xs text-slate-500">审核节点按列表顺序执行；同一节点内按会签或或签。使用正式职责，不填写人员姓名。</p>{s.approvals.map((n, j) => <div key={j} className="grid gap-2 sm:grid-cols-3"><select className="input w-full" aria-label={`阶段${i + 1}审核职责${j + 1}`} value={n.duty} onChange={e => updateStage(i, { approvals: s.approvals.map((r, k) => k === j ? { ...r, duty: e.target.value as typeof n.duty } : r) })}>{duties.map(d => <option key={d.code} value={d.code}>{d.label}</option>)}</select><input className="input w-full" aria-label={`阶段${i + 1}审核名称${j + 1}`} value={n.name} onChange={e => updateStage(i, { approvals: s.approvals.map((r, k) => k === j ? { ...r, name: e.target.value } : r) })} /><select className="input w-full" aria-label={`阶段${i + 1}审核方式${j + 1}`} value={n.mode} onChange={e => updateStage(i, { approvals: s.approvals.map((r, k) => k === j ? { ...r, mode: e.target.value as typeof n.mode } : r) })}><option>会签</option><option>或签</option></select></div>)}<div className="flex flex-wrap gap-2"><Button variant="secondary" aria-label={`上移阶段 ${i + 1}`} disabled={i === 0} onClick={() => change(moveTypeDraftStage(config, i, -1))}>上移阶段</Button><Button variant="secondary" aria-label={`下移阶段 ${i + 1}`} disabled={i === config.stages.length - 1} onClick={() => change(moveTypeDraftStage(config, i, 1))}>下移阶段</Button><Button variant="secondary" aria-label={`为阶段 ${i + 1} 增加行动`} disabled={config.actions.length >= 80} onClick={() => change(addTypeDraftAction(config, s.key))}>为本阶段增加行动</Button><Button variant="secondary" disabled={s.approvals.length >= 12} onClick={() => updateStage(i, { approvals: [...s.approvals, { duty: 'concerned_leader', name: '领导核对', mode: '会签' }] })}>增加审核节点</Button><Button variant="secondary" disabled={s.approvals.length <= 1} onClick={() => updateStage(i, { approvals: s.approvals.slice(0, -1) })}>移除末尾审核节点</Button><Button variant="secondary" disabled={config.stages.length <= 2} onClick={() => change({ ...config, stages: config.stages.filter((_, n) => n !== i), actions: config.actions.filter(a => a.stageKey !== s.key) })}>移除此阶段及草稿行动</Button></div>
          </div>)}<Button variant="secondary" disabled={config.stages.length >= 12 || config.actions.length >= 80} onClick={() => change(addTypeDraftStage(config))}>增加阶段</Button></section>
          <section><h3 className="mb-3 font-semibold">行动及倒排位置</h3>{config.actions.map((a, i) => <div key={i} className="mb-3 grid gap-3 rounded-xl border p-4 sm:grid-cols-2"><label><span className="label">行动编号 {i + 1}</span><input className="input w-full" value={a.key} onChange={e => updateAction(i, { key: e.target.value })} /></label><label><span className="label">行动名称 {i + 1}</span><input className="input w-full" value={a.title} onChange={e => updateAction(i, { title: e.target.value })} /></label><label><span className="label">所属阶段 {i + 1}</span><select className="input w-full" value={a.stageKey} onChange={e => change(reassignTypeDraftAction(config, i, e.target.value))}>{config.stages.map(s => <option key={s.key} value={s.key}>{s.name || s.key}</option>)}</select></label><label><span className="label">负责人职责 {i + 1}</span><select className="input w-full" value={a.duty} onChange={e => updateAction(i, { duty: e.target.value as typeof a.duty })}>{duties.map(d => <option key={d.code} value={d.code}>{d.label}</option>)}</select></label><label><span className="label">周期位置百分比 {i + 1}</span><input type="number" min={0} max={100} className="input w-full" value={a.position} onChange={e => updateAction(i, { position: Number(e.target.value) })} /></label><label className="flex items-center gap-2"><input type="checkbox" checked={a.needLeader} onChange={e => updateAction(i, { needLeader: e.target.checked })} />需领导参与</label><label className="sm:col-span-2"><span className="label">行动交付物 {i + 1}</span><textarea className="textarea w-full" value={a.deliverable} onChange={e => updateAction(i, { deliverable: e.target.value })} /></label><div className="flex flex-wrap gap-2 sm:col-span-2"><Button variant="secondary" aria-label={`上移行动 ${i + 1}`} disabled={i === 0 || config.actions[i - 1]?.stageKey !== a.stageKey} onClick={() => change(moveTypeDraftAction(config, i, -1))}>上移行动</Button><Button variant="secondary" aria-label={`下移行动 ${i + 1}`} disabled={config.actions[i + 1]?.stageKey !== a.stageKey} onClick={() => change(moveTypeDraftAction(config, i, 1))}>下移行动</Button><Button variant="secondary" aria-label={`移除草稿行动 ${i + 1}`} disabled={config.actions.length <= 2} onClick={() => change({ ...config, actions: config.actions.filter((_, n) => n !== i) })}>移除草稿行动</Button></div></div>)}<Button variant="secondary" disabled={config.actions.length >= 80} onClick={() => change(addTypeDraftAction(config, config.stages.at(-1)!.key))}>增加行动</Button><p className="mt-2 text-xs text-slate-500">0% 是周期起点，100% 是最终目标日；按阶段及日期顺序排列，每阶段至少一项成果。最终验收必须落在 100%。上移/下移只调整草稿顺序，不修改原编号和日期比例；调整后请重新核对日期及最终验收。</p></section>
        </fieldset>
        <section className="space-y-3 rounded-xl bg-slate-50 p-4"><h3 className="font-semibold">只读倒排预览</h3><div className="grid gap-3 sm:grid-cols-2"><label><span className="label">预览周期</span><select disabled={busy} className="input w-full" value={cycle} onChange={e => { setCycle(Number(e.target.value)); setPreview(null) }}>{[15, 30, 40, 50].map(d => <option key={d}>{d}</option>)}</select></label><label><span className="label">预览目标日期</span><input disabled={busy} className="input w-full" type="date" value={targetDate} onInput={e => { setTargetDate(e.currentTarget.value); setPreview(null) }} onChange={e => { setTargetDate(e.target.value); setPreview(null) }} /></label></div><Button variant="secondary" disabled={busy || !targetDate} onClick={() => void previewPlan()}>计算预览，不创建任务</Button>{preview?.map(a => <p className="text-sm" key={a.key}>{a.dueDate} · {a.title}</p>)}</section>
        <label className="block"><span className="label">本次操作理由（至少 5 字）</span><textarea disabled={busy} className="textarea w-full" value={reason} onChange={e => { setReason(e.target.value); setAck(false) }} /></label><label className="flex items-start gap-2 text-sm"><input disabled={busy} type="checkbox" checked={ack} onChange={e => setAck(e.target.checked)} />已核对具体版本、登记角色和在途处理规则；审核人不得参与本版编制。发布仍不启用，启用/停用须独立确认，既有项目不自动换版。</label>
      </div>}
    </Modal>
  </div>
}
