import { useMemo } from 'react'
import { shiftDate } from '../../server/src/contracts/fdeWeeklyPlanContract'
import { timeLocal } from '../../server/src/contracts/fdeTimeContract'

export type TimeGridItem = { key: string; id: string | null; title: string; startsAt: string; endsAt: string | null; editable: boolean; allDay?: boolean; warning?: boolean }
export type TimeProposal = { id: string; startsAt: string; durationMinutes: number; method: 'drag' | 'resize' | 'keyboard' }
export function FdeTimeGrid({ weekStart, items, onPropose, onOpen }: { weekStart: string; items: TimeGridItem[]; onPropose: (proposal: TimeProposal) => void; onOpen?: (key: string) => void }) {
  const hourPx = 52
  const days = Array.from({ length: 7 }, (_, i) => shiftDate(weekStart, i))
  const markers = items.filter(item => (item.allDay || !item.endsAt) && days.includes(timeLocal(new Date(item.startsAt)).slice(0, 10)))
  const placements = useMemo(() => {
    const result = new Map<string, { lane: number; count: number }>()
    for (const day of days) {
      const endByLane: number[] = []
      const rows = items.filter((v) => timeLocal(new Date(v.startsAt)).slice(0, 10) === day && v.endsAt).sort((a, b) => a.startsAt.localeCompare(b.startsAt))
      for (const row of rows) { const start = Date.parse(row.startsAt), end = Date.parse(row.endsAt!); let lane = endByLane.findIndex((value) => value <= start); if (lane < 0) lane = endByLane.length; endByLane[lane] = end; result.set(row.key, { lane, count: 1 }) }
      for (const row of rows) result.get(row.key)!.count = Math.max(1, endByLane.length)
    }
    return result
  }, [weekStart, items])
  function minute(value: string) { const local = timeLocal(new Date(value)); return Number(local.slice(11, 13)) * 60 + Number(local.slice(14)) }
  function propose(row: TimeGridItem, day: string, start: number, durationMinutes: number, method: TimeProposal['method']) {
    if (!row.editable || !row.id) return
    onPropose({ id: row.id, startsAt: `${day}T${String(Math.floor(start / 60)).padStart(2, '0')}:${String(start % 60).padStart(2, '0')}`, durationMinutes, method })
  }
  return <><div className="fde-collab-time-grid mt-4 overflow-x-auto rounded-xl border border-slate-200"><p className="border-b bg-slate-50 px-3 py-2 text-xs text-slate-500">07:00—20:00 · 15 分钟步长。可编辑安排支持拖动、底部拉伸；方向键调整时间，Shift + 上下键调整时长。所有调整先确认原因，再保存；业务投影只读。</p><div className="min-w-[840px]"><div className="grid grid-cols-[48px_repeat(7,minmax(0,1fr))] border-b text-center text-xs"><div>时间</div>{days.map((day, i) => <div className="border-l p-2" key={day}>{['周一','周二','周三','周四','周五','周六','周日'][i]}<br /><small>{Number(day.slice(8))}</small></div>)}</div>{markers.length>0&&<div className="grid grid-cols-[48px_repeat(7,minmax(0,1fr))] border-b bg-slate-50" aria-label="日期与截止标记，不占用时间"><div className="p-1 text-[10px] text-slate-500">日期/<br />截止</div>{days.map(day=><div key={day} className="min-w-0 space-y-1 border-l p-1">{markers.filter(item=>timeLocal(new Date(item.startsAt)).slice(0,10)===day).map(item=><p key={item.key} className="break-words rounded border border-[#a8c5c3] bg-[#e7f1ef] p-1 text-[10px] text-[#315f68]">{item.title}{!item.allDay&&` · ${timeLocal(new Date(item.startsAt)).slice(11)}`}</p>)}</div>)}</div>}<div className="grid grid-cols-[48px_repeat(7,minmax(0,1fr))]"><div className="relative text-[10px] text-slate-400" style={{height:13*hourPx}}>{Array.from({length:14},(_,i)=><span key={i} className="absolute right-1" style={{top:i*hourPx}}>{String(i+7).padStart(2,'0')}:00</span>)}</div>{days.map((day) => <div key={day} className="fde-collab-time-track relative border-l" style={{height:13*hourPx,backgroundImage:'repeating-linear-gradient(to bottom, transparent 0, transparent 51px, #e2e8f0 51px, #e2e8f0 52px)'}} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); let data: { key: string; resize: boolean }; try { data=JSON.parse(event.dataTransfer.getData('application/x-fde-time')) } catch { return } const row=items.find((v)=>v.key===data.key); if(!row?.editable||!row.endsAt)return; const target=420+Math.round((event.clientY-event.currentTarget.getBoundingClientRect().top)/(hourPx/4))*15; const duration=(Date.parse(row.endsAt)-Date.parse(row.startsAt))/60000; propose(row,day,data.resize?minute(row.startsAt):target,data.resize?target-minute(row.startsAt):duration,data.resize?'resize':'drag') }}>
      {items.filter((row) => !row.allDay && row.endsAt && timeLocal(new Date(row.startsAt)).slice(0,10)===day && minute(row.startsAt)>=420 && minute(row.startsAt)+(Date.parse(row.endsAt!)-Date.parse(row.startsAt))/60000<=1200).map((row)=>{const start=minute(row.startsAt),duration=(Date.parse(row.endsAt!)-Date.parse(row.startsAt))/60000,p=placements.get(row.key)??{lane:0,count:1};return <div key={row.key} data-editable={row.editable} className={`fde-collab-time-block absolute overflow-hidden rounded-md border p-1 text-[10px] ${row.warning?'border-amber-300 bg-amber-50':'border-[#a8c5c3] bg-[#e7f1ef]'}`} style={{top:(start-420)*hourPx/60,height:Math.max(24,duration*hourPx/60),left:`${p.lane*100/p.count}%`,width:`${100/p.count}%`}}><button type="button" draggable={row.editable} aria-label={`${row.title} ${timeLocal(new Date(row.startsAt)).slice(11)}`} className={`w-full text-left ${row.editable?'cursor-move':'cursor-default'}`} onClick={()=>onOpen?.(row.key)} onDragStart={(event)=>event.dataTransfer.setData('application/x-fde-time',JSON.stringify({key:row.key,resize:false}))} onKeyDown={(event)=>{if(!row.editable||!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(event.key))return;event.preventDefault();const delta=event.key==='ArrowUp'?-15:event.key==='ArrowDown'?15:0;propose(row,shiftDate(day,event.key==='ArrowLeft'?-1:event.key==='ArrowRight'?1:0),event.shiftKey?start:start+delta,event.shiftKey?duration+delta:duration,'keyboard')}}><span className="fde-collab-time-block-head"><strong>{timeLocal(new Date(row.startsAt)).slice(11)}</strong><span>{duration}m</span></span><strong className="fde-collab-time-title block truncate">{row.title}</strong></button>{row.editable&&<span role="button" aria-label={`拉伸 ${row.title}`} draggable className="absolute inset-x-0 bottom-0 h-2 cursor-ns-resize bg-[#315f68]/20" onDragStart={(event)=>{event.stopPropagation();event.dataTransfer.setData('application/x-fde-time',JSON.stringify({key:row.key,resize:true}))}} />}</div>})}
    </div>)}</div></div></div><div className="fde-collab-time-mobile">{days.map((day,index)=>{const rows=items.filter(item=>{const start=timeLocal(new Date(item.startsAt));return item.endsAt?start.slice(0,10)<=day&&timeLocal(new Date(item.endsAt))>day+'T00:00':start.slice(0,10)===day});return <section key={day}><header><strong>{['周一','周二','周三','周四','周五','周六','周日'][index]} · {Number(day.slice(8))}</strong><small>{rows.length} 项</small></header><div>{rows.length?rows.map(row=><button key={row.key} onClick={()=>onOpen?.(row.key)}><time>{row.allDay?'全天':timeLocal(new Date(row.startsAt)).slice(11)}</time><span><strong>{row.title}</strong><small>{!row.endsAt?'日期 / 截止':row.editable?'个人安排 · 可调整':'业务来源 · 只读'}</small></span></button>):<p>暂无安排</p>}</div></section>})}</div></>
}
