import { useEffect, useState } from 'react'
import { apiGet, apiPost } from '../lib/api'
import { Button, Card } from './ui'
import type { Project, ProjectFile } from '../types'

export function PostInvestmentPanel({ project, files, leaders }: { project: Project; files: ProjectFile[]; leaders: Array<{ id: string; name: string; role: string }> }) {
  const [content, setContent] = useState(''), [fileIds, setFileIds] = useState<string[]>([]), [leaderIds, setLeaderIds] = useState<string[]>([]), [updates, setUpdates] = useState<Array<{ id: string; content: string; author: string; createdAt: string }>>([]), [saving, setSaving] = useState(false)
  const load = () => apiGet<{ list: typeof updates }>(`/projects/${project.id}/post-investment-updates`).then(value => setUpdates(value.list)).catch(() => setUpdates([]))
  useEffect(() => { void load() }, [project.id])
  const save = async (remind: boolean) => { setSaving(true); try { await apiPost(`/projects/${project.id}/post-investment-updates`, { content, fileIds, leaderIds: remind ? leaderIds : [] }); setContent(''); setFileIds([]); load() } finally { setSaving(false) } }
  return <div className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><Card className="p-5"><h3 className="font-semibold">投后文件</h3><p className="mt-1 text-sm text-slate-500">在项目资料中上传交割、经营和董事会文件后，可在右侧关联。</p><div className="mt-4 space-y-2">{files.map(file => <label className="flex gap-2 text-sm" key={file.id}><input type="checkbox" checked={fileIds.includes(file.id)} onChange={() => setFileIds(ids => ids.includes(file.id) ? ids.filter(id => id !== file.id) : [...ids, file.id])} />{file.name}</label>)}</div></Card><Card className="p-5"><h3 className="font-semibold">本次投后更新</h3><textarea className="input mt-3 min-h-32 w-full" value={content} onChange={e => setContent(e.target.value)} placeholder="记录经营、财务、融资、风险和需要协调的事项…" /><div className="mt-3 flex flex-wrap gap-3">{leaders.filter(item => item.role === '董事长' || item.role === '总裁').map(leader => <label className="text-sm" key={leader.id}><input type="checkbox" checked={leaderIds.includes(leader.id)} onChange={() => setLeaderIds(ids => ids.includes(leader.id) ? ids.filter(id => id !== leader.id) : [...ids, leader.id])} /> {leader.name}</label>)}</div><div className="mt-4 flex gap-2"><Button disabled={!content.trim()} loading={saving} onClick={() => save(false)}>保存说明</Button><Button disabled={!content.trim() || !leaderIds.length} loading={saving} onClick={() => save(true)}>保存并提醒领导</Button></div><div className="mt-6 space-y-3">{updates.map(update => <div className="rounded border p-3 text-sm" key={update.id}><b>{update.author}</b><span className="ml-2 text-slate-400">{new Date(update.createdAt).toLocaleString()}</span><p className="mt-2 whitespace-pre-wrap">{update.content}</p></div>)}</div></Card></div>
}
