CREATE TABLE `sbl_lead_pipeline_entity_matches` (
  `id` varchar(36) NOT NULL,
  `match_key` varchar(64) NOT NULL,
  `event_id` varchar(64) NOT NULL,
  `decision_id` varchar(36) DEFAULT NULL,
  `review_id` varchar(36) DEFAULT NULL,
  `subject_type` varchar(16) DEFAULT NULL,
  `subject_name` varchar(128) NOT NULL,
  `normalized_subject_name` varchar(128) NOT NULL,
  `match_type` varchar(32) NOT NULL,
  `candidate_lead_id` varchar(36) DEFAULT NULL,
  `candidate_name` varchar(128) DEFAULT NULL,
  `candidate_company_name` varchar(128) DEFAULT NULL,
  `score` int DEFAULT NULL,
  `status` varchar(16) NOT NULL,
  `resolution_type` varchar(16) NOT NULL DEFAULT 'pending',
  `resolution_decision_id` varchar(36) DEFAULT NULL,
  `aliases` json NOT NULL DEFAULT (JSON_ARRAY()),
  `metadata` json NOT NULL DEFAULT (JSON_OBJECT()),
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `resolved_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_lp_entity_matches_key` (`match_key`),
  KEY `idx_lp_entity_matches_event` (`event_id`,`status`,`created_at`),
  KEY `idx_lp_entity_matches_candidate` (`candidate_lead_id`,`status`,`created_at`),
  KEY `idx_lp_entity_matches_subject` (`normalized_subject_name`,`status`,`created_at`),
  KEY `idx_lp_entity_matches_decision` (`decision_id`),
  KEY `idx_lp_entity_matches_review` (`review_id`),
  KEY `idx_lp_entity_matches_resolution_decision` (`resolution_decision_id`),
  CONSTRAINT `sbl_lp_entity_matches_event_fk` FOREIGN KEY (`event_id`) REFERENCES `sbl_lead_pipeline_raw_events` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `sbl_lp_entity_matches_decision_fk` FOREIGN KEY (`decision_id`) REFERENCES `sbl_lead_pipeline_decisions` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `sbl_lp_entity_matches_review_fk` FOREIGN KEY (`review_id`) REFERENCES `sbl_lead_pipeline_reviews` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `sbl_lp_entity_matches_candidate_fk` FOREIGN KEY (`candidate_lead_id`) REFERENCES `sbl_leads` (`id`) ON DELETE SET NULL,
  CONSTRAINT `sbl_lp_entity_matches_resolution_decision_fk` FOREIGN KEY (`resolution_decision_id`) REFERENCES `sbl_lead_pipeline_decisions` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `ck_lp_entity_matches_score` CHECK (`score` IS NULL OR (`score` >= 0 AND `score` <= 10000)),
  CONSTRAINT `ck_lp_entity_matches_status` CHECK (`status` IN ('candidate','ambiguous','selected','created','rejected')),
  CONSTRAINT `ck_lp_entity_matches_resolution` CHECK (`resolution_type` IN ('pending','automatic','manual','created','rejected'))
);
