CREATE TABLE `sbl_lead_intake_files` (
  `id` varchar(36) NOT NULL,
  `kind` varchar(16) NOT NULL,
  `idempotency_key` varchar(64) NOT NULL,
  `original_name` varchar(255) NOT NULL,
  `type_label` varchar(32) NOT NULL,
  `content_type` varchar(255) NOT NULL,
  `byte_size` bigint NOT NULL,
  `sha256` varchar(64) NOT NULL,
  `storage_path` text NOT NULL,
  `status` varchar(24) NOT NULL DEFAULT 'uploaded',
  `stage` varchar(32) NOT NULL DEFAULT 'uploaded',
  `progress` int NOT NULL DEFAULT 0,
  `execution_attempts` int NOT NULL DEFAULT 0,
  `next_attempt_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `lease_owner` varchar(128),
  `lease_expires_at` datetime(3),
  `last_error` text,
  `event_id` varchar(64),
  `lead_id` varchar(36),
  `review_id` varchar(36),
  `uploaded_by` varchar(36) NOT NULL,
  `uploaded_by_name` varchar(64) NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `completed_at` datetime(3),
  CONSTRAINT `sbl_lead_intake_files_pk` PRIMARY KEY (`id`),
  CONSTRAINT `sbl_lead_intake_files_event_fk` FOREIGN KEY (`event_id`) REFERENCES `sbl_lead_pipeline_raw_events` (`id`) ON DELETE SET NULL,
  CONSTRAINT `sbl_lead_intake_files_lead_fk` FOREIGN KEY (`lead_id`) REFERENCES `sbl_leads` (`id`) ON DELETE SET NULL,
  CONSTRAINT `sbl_lead_intake_files_user_fk` FOREIGN KEY (`uploaded_by`) REFERENCES `sbl_users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `uq_lead_intake_files_idempotency` UNIQUE (`idempotency_key`),
  INDEX `idx_lead_intake_files_due` (`kind`, `status`, `next_attempt_at`),
  INDEX `idx_lead_intake_files_uploader` (`uploaded_by`, `created_at`),
  INDEX `idx_lead_intake_files_lease` (`lease_expires_at`)
);
--> statement-breakpoint
CREATE TABLE `sbl_lead_import_batches` (
  `id` varchar(36) NOT NULL,
  `file_id` varchar(36) NOT NULL,
  `template_version` varchar(32) NOT NULL DEFAULT 'lead-import-v1',
  `status` varchar(24) NOT NULL DEFAULT 'preview',
  `total_rows` int NOT NULL DEFAULT 0,
  `valid_rows` int NOT NULL DEFAULT 0,
  `error_rows` int NOT NULL DEFAULT 0,
  `committed_rows` int NOT NULL DEFAULT 0,
  `review_rows` int NOT NULL DEFAULT 0,
  `failed_rows` int NOT NULL DEFAULT 0,
  `created_by` varchar(36) NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `completed_at` datetime(3),
  CONSTRAINT `sbl_lead_import_batches_pk` PRIMARY KEY (`id`),
  CONSTRAINT `sbl_lead_import_batches_file_fk` FOREIGN KEY (`file_id`) REFERENCES `sbl_lead_intake_files` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `sbl_lead_import_batches_user_fk` FOREIGN KEY (`created_by`) REFERENCES `sbl_users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `uq_lead_import_batches_file` UNIQUE (`file_id`),
  INDEX `idx_lead_import_batches_creator` (`created_by`, `created_at`)
);
--> statement-breakpoint
CREATE TABLE `sbl_lead_import_rows` (
  `id` varchar(36) NOT NULL,
  `batch_id` varchar(36) NOT NULL,
  `row_number` int NOT NULL,
  `raw_data` json NOT NULL DEFAULT (JSON_OBJECT()),
  `normalized_data` json NOT NULL DEFAULT (JSON_OBJECT()),
  `validation_errors` json NOT NULL DEFAULT (JSON_ARRAY()),
  `status` varchar(24) NOT NULL DEFAULT 'valid',
  `event_id` varchar(64),
  `lead_id` varchar(36),
  `review_id` varchar(36),
  `result_message` text,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT `sbl_lead_import_rows_pk` PRIMARY KEY (`id`),
  CONSTRAINT `sbl_lead_import_rows_batch_fk` FOREIGN KEY (`batch_id`) REFERENCES `sbl_lead_import_batches` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sbl_lead_import_rows_event_fk` FOREIGN KEY (`event_id`) REFERENCES `sbl_lead_pipeline_raw_events` (`id`) ON DELETE SET NULL,
  CONSTRAINT `sbl_lead_import_rows_lead_fk` FOREIGN KEY (`lead_id`) REFERENCES `sbl_leads` (`id`) ON DELETE SET NULL,
  CONSTRAINT `uq_lead_import_rows_batch_row` UNIQUE (`batch_id`, `row_number`),
  INDEX `idx_lead_import_rows_status` (`batch_id`, `status`)
);
