ALTER TABLE `sbl_lead_score_jobs`
  ADD COLUMN `enrichment_snapshot_id` varchar(36),
  ADD COLUMN `snapshot_hash` varchar(64),
  ADD COLUMN `rating_schema_version` varchar(64);
--> statement-breakpoint
CREATE TABLE `sbl_lead_entities` (
  `id` varchar(36) NOT NULL,
  `lead_id` varchar(36) NOT NULL,
  `entity_type` varchar(16) NOT NULL,
  `canonical_name` varchar(255) NOT NULL,
  `normalized_name` varchar(255) NOT NULL,
  `status` varchar(16) NOT NULL,
  `aliases` json NOT NULL DEFAULT (JSON_ARRAY()),
  `identifiers` json NOT NULL DEFAULT (JSON_OBJECT()),
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT `sbl_lead_entities_pk` PRIMARY KEY (`id`),
  CONSTRAINT `sbl_lead_entities_lead_fk` FOREIGN KEY (`lead_id`) REFERENCES `sbl_leads` (`id`) ON DELETE CASCADE,
  CONSTRAINT `uq_lead_entities_identity` UNIQUE (`lead_id`,`entity_type`,`normalized_name`),
  INDEX `idx_lead_entities_lead` (`lead_id`,`entity_type`,`status`)
);
--> statement-breakpoint
CREATE TABLE `sbl_lead_entity_relations` (
  `id` varchar(36) NOT NULL,
  `lead_id` varchar(36) NOT NULL,
  `from_entity_id` varchar(36) NOT NULL,
  `to_entity_id` varchar(36) NOT NULL,
  `relation_type` varchar(48) NOT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'claimed',
  `evidence_fact_id` varchar(36),
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT `sbl_lead_entity_relations_pk` PRIMARY KEY (`id`),
  CONSTRAINT `sbl_lead_entity_relations_lead_fk` FOREIGN KEY (`lead_id`) REFERENCES `sbl_leads` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sbl_lead_entity_relations_from_fk` FOREIGN KEY (`from_entity_id`) REFERENCES `sbl_lead_entities` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sbl_lead_entity_relations_to_fk` FOREIGN KEY (`to_entity_id`) REFERENCES `sbl_lead_entities` (`id`) ON DELETE CASCADE,
  CONSTRAINT `uq_lead_entity_relations_identity` UNIQUE (`from_entity_id`,`to_entity_id`,`relation_type`),
  INDEX `idx_lead_entity_relations_lead` (`lead_id`,`relation_type`,`status`)
);
--> statement-breakpoint
CREATE TABLE `sbl_lead_enrichment_jobs` (
  `id` varchar(36) NOT NULL,
  `lead_id` varchar(36) NOT NULL,
  `trigger_type` varchar(48) NOT NULL,
  `trigger_event_id` varchar(64),
  `idempotency_key` varchar(64) NOT NULL,
  `entity_id` varchar(36),
  `entity_type` varchar(16) NOT NULL DEFAULT 'unknown',
  `entity_status` varchar(16) NOT NULL DEFAULT 'missing',
  `status` varchar(24) NOT NULL DEFAULT 'queued',
  `priority` int NOT NULL DEFAULT 100,
  `execution_attempts` int NOT NULL DEFAULT 0,
  `next_attempt_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `lease_owner` varchar(128),
  `lease_expires_at` datetime(3),
  `last_error` text,
  `started_at` datetime(3),
  `completed_at` datetime(3),
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT `sbl_lead_enrichment_jobs_pk` PRIMARY KEY (`id`),
  CONSTRAINT `sbl_lead_enrichment_jobs_lead_fk` FOREIGN KEY (`lead_id`) REFERENCES `sbl_leads` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sbl_lead_enrichment_jobs_event_fk` FOREIGN KEY (`trigger_event_id`) REFERENCES `sbl_lead_pipeline_raw_events` (`id`) ON DELETE SET NULL,
  CONSTRAINT `sbl_lead_enrichment_jobs_entity_fk` FOREIGN KEY (`entity_id`) REFERENCES `sbl_lead_entities` (`id`) ON DELETE SET NULL,
  CONSTRAINT `uq_lead_enrichment_jobs_idempotency` UNIQUE (`idempotency_key`),
  INDEX `idx_lead_enrichment_jobs_due` (`status`, `priority`, `next_attempt_at`),
  INDEX `idx_lead_enrichment_jobs_lead` (`lead_id`, `created_at`),
  INDEX `idx_lead_enrichment_jobs_lease` (`lease_expires_at`)
);
--> statement-breakpoint
CREATE TABLE `sbl_lead_enrichment_topic_runs` (
  `id` varchar(36) NOT NULL,
  `job_id` varchar(36) NOT NULL,
  `lead_id` varchar(36) NOT NULL,
  `topic_key` varchar(48) NOT NULL,
  `status` varchar(24) NOT NULL DEFAULT 'queued',
  `prompt_version` varchar(64),
  `model` varchar(128),
  `toolset_version` varchar(64),
  `query_plan` json NOT NULL DEFAULT (JSON_ARRAY()),
  `metrics` json NOT NULL DEFAULT (JSON_OBJECT()),
  `execution_attempts` int NOT NULL DEFAULT 0,
  `next_attempt_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `lease_owner` varchar(128),
  `lease_expires_at` datetime(3),
  `last_error` text,
  `started_at` datetime(3),
  `completed_at` datetime(3),
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT `sbl_lead_enrichment_topic_runs_pk` PRIMARY KEY (`id`),
  CONSTRAINT `sbl_lead_enrichment_topic_runs_job_fk` FOREIGN KEY (`job_id`) REFERENCES `sbl_lead_enrichment_jobs` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sbl_lead_enrichment_topic_runs_lead_fk` FOREIGN KEY (`lead_id`) REFERENCES `sbl_leads` (`id`) ON DELETE CASCADE,
  CONSTRAINT `uq_lead_enrichment_topic_job` UNIQUE (`job_id`, `topic_key`),
  INDEX `idx_lead_enrichment_topic_due` (`status`, `next_attempt_at`),
  INDEX `idx_lead_enrichment_topic_lead` (`lead_id`, `topic_key`, `created_at`),
  INDEX `idx_lead_enrichment_topic_lease` (`lease_expires_at`)
);
--> statement-breakpoint
CREATE TABLE `sbl_lead_topic_search_cache` (
  `cache_key` varchar(64) NOT NULL,
  `subject_fingerprint` varchar(64) NOT NULL,
  `topic_key` varchar(48) NOT NULL,
  `prompt_version` varchar(64) NOT NULL,
  `query_plan_hash` varchar(64) NOT NULL,
  `model` varchar(128) NOT NULL,
  `result` json NOT NULL,
  `expires_at` datetime(3) NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT `sbl_lead_topic_search_cache_pk` PRIMARY KEY (`cache_key`),
  INDEX `idx_lead_topic_search_cache_subject` (`subject_fingerprint`,`topic_key`,`expires_at`),
  INDEX `idx_lead_topic_search_cache_expiry` (`expires_at`)
);
--> statement-breakpoint
CREATE TABLE `sbl_lead_facts` (
  `id` varchar(36) NOT NULL,
  `lead_id` varchar(36) NOT NULL,
  `topic_run_id` varchar(36),
  `topic_key` varchar(48) NOT NULL,
  `subject_type` varchar(24) NOT NULL,
  `subject_id` varchar(128) NOT NULL,
  `fact_key` varchar(128) NOT NULL,
  `value` json NOT NULL,
  `value_hash` varchar(64) NOT NULL,
  `unit` varchar(32),
  `currency` varchar(16),
  `period_start` varchar(32),
  `period_end` varchar(32),
  `scope` varchar(128),
  `evidence_level` varchar(4) NOT NULL,
  `verification_status` varchar(24) NOT NULL,
  `version` int NOT NULL DEFAULT 1,
  `supersedes_fact_id` varchar(36),
  `is_current` boolean NOT NULL DEFAULT true,
  `valid_from` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `valid_until` datetime(3),
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT `sbl_lead_facts_pk` PRIMARY KEY (`id`),
  CONSTRAINT `sbl_lead_facts_lead_fk` FOREIGN KEY (`lead_id`) REFERENCES `sbl_leads` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sbl_lead_facts_topic_run_fk` FOREIGN KEY (`topic_run_id`) REFERENCES `sbl_lead_enrichment_topic_runs` (`id`) ON DELETE SET NULL,
  CONSTRAINT `sbl_lead_facts_supersedes_fk` FOREIGN KEY (`supersedes_fact_id`) REFERENCES `sbl_lead_facts` (`id`) ON DELETE SET NULL,
  CONSTRAINT `uq_lead_facts_version` UNIQUE (`lead_id`, `subject_id`, `fact_key`, `version`),
  INDEX `idx_lead_facts_current` (`lead_id`, `is_current`, `topic_key`),
  INDEX `idx_lead_facts_value` (`lead_id`, `fact_key`, `value_hash`)
);
--> statement-breakpoint
CREATE TABLE `sbl_lead_source_documents` (
  `id` varchar(36) NOT NULL,
  `lead_id` varchar(36),
  `canonical_url` text NOT NULL,
  `canonical_url_hash` varchar(64) NOT NULL,
  `final_url` text NOT NULL,
  `fetch_status` varchar(24) NOT NULL,
  `http_status` int,
  `content_type` varchar(96),
  `title` text,
  `publisher` varchar(255),
  `published_at` datetime(3),
  `content_hash` varchar(64) NOT NULL,
  `extracted_text` longtext NOT NULL,
  `error_code` varchar(64),
  `accessed_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at` datetime(3) NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT `sbl_lead_source_documents_pk` PRIMARY KEY (`id`),
  CONSTRAINT `sbl_lead_source_documents_lead_fk` FOREIGN KEY (`lead_id`) REFERENCES `sbl_leads` (`id`) ON DELETE CASCADE,
  CONSTRAINT `uq_lead_source_documents_version` UNIQUE (`canonical_url_hash`, `content_hash`),
  INDEX `idx_lead_source_documents_cache` (`canonical_url_hash`, `fetch_status`, `expires_at`),
  INDEX `idx_lead_source_documents_lead` (`lead_id`, `created_at`)
);
--> statement-breakpoint
CREATE TABLE `sbl_lead_fact_evidence` (
  `id` varchar(36) NOT NULL,
  `fact_id` varchar(36) NOT NULL,
  `source_document_id` varchar(36),
  `source_url` text NOT NULL,
  `canonical_url_hash` varchar(64) NOT NULL,
  `source_type` varchar(32) NOT NULL,
  `content_type` varchar(32) NOT NULL DEFAULT 'unknown',
  `title` text,
  `publisher` varchar(255),
  `quote` longtext NOT NULL,
  `locator` varchar(255),
  `page_hash` varchar(64),
  `reliability` varchar(16),
  `published_at` datetime(3),
  `accessed_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT `sbl_lead_fact_evidence_pk` PRIMARY KEY (`id`),
  CONSTRAINT `sbl_lead_fact_evidence_fact_fk` FOREIGN KEY (`fact_id`) REFERENCES `sbl_lead_facts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sbl_lead_fact_evidence_document_fk` FOREIGN KEY (`source_document_id`) REFERENCES `sbl_lead_source_documents` (`id`) ON DELETE SET NULL,
  CONSTRAINT `uq_lead_fact_evidence_source` UNIQUE (`fact_id`, `canonical_url_hash`),
  INDEX `idx_lead_fact_evidence_fact` (`fact_id`, `created_at`),
  INDEX `idx_lead_fact_evidence_source` (`canonical_url_hash`)
);
--> statement-breakpoint
CREATE TABLE `sbl_lead_fact_conflicts` (
  `id` varchar(36) NOT NULL,
  `lead_id` varchar(36) NOT NULL,
  `topic_key` varchar(48) NOT NULL,
  `fact_key` varchar(128) NOT NULL,
  `status` varchar(24) NOT NULL DEFAULT 'open',
  `severity` varchar(16) NOT NULL DEFAULT 'material',
  `candidate_fact_ids` json NOT NULL DEFAULT (JSON_ARRAY()),
  `automatic_reason` text,
  `resolution` json NOT NULL DEFAULT (JSON_OBJECT()),
  `resolved_by` varchar(36),
  `resolved_at` datetime(3),
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT `sbl_lead_fact_conflicts_pk` PRIMARY KEY (`id`),
  CONSTRAINT `sbl_lead_fact_conflicts_lead_fk` FOREIGN KEY (`lead_id`) REFERENCES `sbl_leads` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sbl_lead_fact_conflicts_user_fk` FOREIGN KEY (`resolved_by`) REFERENCES `sbl_users` (`id`) ON DELETE SET NULL,
  INDEX `idx_lead_fact_conflicts_status` (`lead_id`, `status`, `severity`)
);
--> statement-breakpoint
CREATE TABLE `sbl_lead_enrichment_snapshots` (
  `id` varchar(36) NOT NULL,
  `lead_id` varchar(36) NOT NULL,
  `job_id` varchar(36) NOT NULL,
  `schema_version` varchar(64) NOT NULL,
  `status` varchar(24) NOT NULL,
  `snapshot_hash` varchar(64) NOT NULL,
  `topic_states` json NOT NULL DEFAULT (JSON_OBJECT()),
  `subject_profile` json NOT NULL DEFAULT (JSON_OBJECT()),
  `facts` json NOT NULL DEFAULT (JSON_ARRAY()),
  `evidence_index` json NOT NULL DEFAULT (JSON_OBJECT()),
  `gaps` json NOT NULL DEFAULT (JSON_ARRAY()),
  `conflicts` json NOT NULL DEFAULT (JSON_ARRAY()),
  `coverage` int NOT NULL DEFAULT 0,
  `frozen_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT `sbl_lead_enrichment_snapshots_pk` PRIMARY KEY (`id`),
  CONSTRAINT `sbl_lead_enrichment_snapshots_lead_fk` FOREIGN KEY (`lead_id`) REFERENCES `sbl_leads` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sbl_lead_enrichment_snapshots_job_fk` FOREIGN KEY (`job_id`) REFERENCES `sbl_lead_enrichment_jobs` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `uq_lead_enrichment_snapshot_hash` UNIQUE (`lead_id`, `snapshot_hash`, `schema_version`),
  INDEX `idx_lead_enrichment_snapshots_lead` (`lead_id`, `created_at`),
  INDEX `idx_lead_enrichment_snapshots_job` (`job_id`)
);
--> statement-breakpoint
CREATE TABLE `sbl_lead_rating_history` (
  `id` varchar(36) NOT NULL,
  `lead_id` varchar(36) NOT NULL,
  `snapshot_id` varchar(36) NOT NULL,
  `snapshot_hash` varchar(64) NOT NULL,
  `rating_schema_version` varchar(64) NOT NULL,
  `workflow` varchar(64) NOT NULL,
  `prompt_version` varchar(128) NOT NULL,
  `model` varchar(128) NOT NULL,
  `status` varchar(24) NOT NULL,
  `result` json NOT NULL,
  `completed_at` datetime(3) NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT `sbl_lead_rating_history_pk` PRIMARY KEY (`id`),
  CONSTRAINT `sbl_lead_rating_history_lead_fk` FOREIGN KEY (`lead_id`) REFERENCES `sbl_leads` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sbl_lead_rating_history_snapshot_fk` FOREIGN KEY (`snapshot_id`) REFERENCES `sbl_lead_enrichment_snapshots` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `uq_lead_rating_history_snapshot` UNIQUE (`lead_id`,`snapshot_hash`,`rating_schema_version`),
  INDEX `idx_lead_rating_history_lead` (`lead_id`,`completed_at`),
  INDEX `idx_lead_rating_history_snapshot` (`snapshot_id`)
);
