CREATE TABLE `sbl_lead_source_candidates` (
  `id` varchar(36) NOT NULL,
  `source_type` varchar(32) NOT NULL,
  `source_project_id` text NOT NULL,
  `source_project_id_hash` varchar(64) NOT NULL,
  `canonical_url` text NOT NULL,
  `project_name` varchar(128) NOT NULL,
  `company_name` varchar(128),
  `founded_at` date,
  `source_industries` json NOT NULL DEFAULT (JSON_ARRAY()),
  `sector_labels` json NOT NULL DEFAULT (JSON_ARRAY()),
  `scope_status` varchar(32) NOT NULL,
  `scope_reasons` json NOT NULL DEFAULT (JSON_ARRAY()),
  `rules_version` varchar(32) NOT NULL,
  `first_seen_at` datetime(3) NOT NULL,
  `last_seen_at` datetime(3) NOT NULL,
  `fetched_at` datetime(3) NOT NULL,
  `content_hash` varchar(64) NOT NULL,
  `raw_event_id` varchar(64) NOT NULL,
  `admission_status` varchar(24) NOT NULL DEFAULT 'not_ready',
  `processing_started_at` datetime(3),
  `admitted_at` datetime(3),
  `admitted_lead_id` varchar(36),
  `attempts` int NOT NULL DEFAULT 0,
  `last_error` text,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT `sbl_lead_source_candidates_id_pk` PRIMARY KEY (`id`),
  CONSTRAINT `fk_lead_source_candidates_event` FOREIGN KEY (`raw_event_id`) REFERENCES `sbl_lead_pipeline_raw_events` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_lead_source_candidates_lead` FOREIGN KEY (`admitted_lead_id`) REFERENCES `sbl_leads` (`id`) ON DELETE SET NULL,
  UNIQUE KEY `uq_lead_source_candidates_source` (`source_type`,`source_project_id_hash`),
  KEY `idx_lead_source_candidates_admission` (`admission_status`,`first_seen_at`),
  KEY `idx_lead_source_candidates_scope` (`scope_status`,`last_seen_at`),
  KEY `idx_lead_source_candidates_lead` (`admitted_lead_id`),
  CHECK (`scope_status` IN ('eligible','founded_before_2025','founded_at_pending','sector_unmatched','registration_ineligible')),
  CHECK (`admission_status` IN ('not_ready','ready','processing','review','admitted'))
);
