CREATE TABLE `sbl_lead_institution_dictionary` (
  `id` varchar(36) NOT NULL,
  `canonical_name` varchar(255) NOT NULL,
  `aliases` json NOT NULL DEFAULT (JSON_ARRAY()),
  `institution_type` varchar(64) NOT NULL,
  `tier` varchar(32),
  `major` boolean NOT NULL DEFAULT false,
  `status` varchar(16) NOT NULL DEFAULT 'active',
  `version` int NOT NULL DEFAULT 1,
  `updated_by` varchar(36),
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_lead_institution_dictionary_user` FOREIGN KEY (`updated_by`) REFERENCES `sbl_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `ck_lead_institution_dictionary_status` CHECK (`status` IN ('active','inactive')),
  CONSTRAINT `ck_lead_institution_dictionary_version` CHECK (`version` > 0),
  UNIQUE KEY `uq_lead_institution_dictionary_name` (`canonical_name`),
  INDEX `idx_lead_institution_dictionary_status` (`status`, `major`)
);
--> statement-breakpoint
CREATE TABLE `sbl_lead_customer_dictionary` (
  `id` varchar(36) NOT NULL,
  `canonical_name` varchar(255) NOT NULL,
  `aliases` json NOT NULL DEFAULT (JSON_ARRAY()),
  `tier` varchar(8) NOT NULL,
  `confidentiality` varchar(16) NOT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'active',
  `version` int NOT NULL DEFAULT 1,
  `updated_by` varchar(36),
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_lead_customer_dictionary_user` FOREIGN KEY (`updated_by`) REFERENCES `sbl_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `ck_lead_customer_dictionary_tier` CHECK (`tier` IN ('A','B','C')),
  CONSTRAINT `ck_lead_customer_dictionary_confidentiality` CHECK (`confidentiality` IN ('public','confidential','restricted')),
  CONSTRAINT `ck_lead_customer_dictionary_status` CHECK (`status` IN ('active','inactive')),
  CONSTRAINT `ck_lead_customer_dictionary_version` CHECK (`version` > 0),
  UNIQUE KEY `uq_lead_customer_dictionary_name` (`canonical_name`),
  INDEX `idx_lead_customer_dictionary_status` (`status`, `confidentiality`, `tier`)
);
--> statement-breakpoint
CREATE TABLE `sbl_lead_industry_dictionary` (
  `id` varchar(36) NOT NULL,
  `canonical_name` varchar(255) NOT NULL,
  `aliases` json NOT NULL DEFAULT (JSON_ARRAY()),
  `level1` varchar(128) NOT NULL,
  `level2` varchar(128),
  `segment` varchar(255),
  `chain_position` varchar(128),
  `status` varchar(16) NOT NULL DEFAULT 'active',
  `version` int NOT NULL DEFAULT 1,
  `updated_by` varchar(36),
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_lead_industry_dictionary_user` FOREIGN KEY (`updated_by`) REFERENCES `sbl_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `ck_lead_industry_dictionary_status` CHECK (`status` IN ('active','inactive')),
  CONSTRAINT `ck_lead_industry_dictionary_version` CHECK (`version` > 0),
  UNIQUE KEY `uq_lead_industry_dictionary_name` (`canonical_name`),
  INDEX `idx_lead_industry_dictionary_status` (`status`, `level1`, `level2`)
);
--> statement-breakpoint
CREATE TABLE `sbl_lead_academic_institution_dictionary` (
  `id` varchar(36) NOT NULL,
  `canonical_name` varchar(255) NOT NULL,
  `aliases` json NOT NULL DEFAULT (JSON_ARRAY()),
  `institution_type` varchar(64) NOT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'active',
  `version` int NOT NULL DEFAULT 1,
  `updated_by` varchar(36),
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_lead_academic_institution_dictionary_user` FOREIGN KEY (`updated_by`) REFERENCES `sbl_users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `ck_lead_academic_institution_dictionary_status` CHECK (`status` IN ('active','inactive')),
  CONSTRAINT `ck_lead_academic_institution_dictionary_version` CHECK (`version` > 0),
  UNIQUE KEY `uq_lead_academic_institution_dictionary_name` (`canonical_name`),
  INDEX `idx_lead_academic_institution_dictionary_status` (`status`, `institution_type`)
);
--> statement-breakpoint
CREATE TABLE `sbl_lead_investment_profile_projections` (
  `lead_id` varchar(36) NOT NULL,
  `schema_version` varchar(64) NOT NULL,
  `snapshot_id` varchar(36) NOT NULL,
  `snapshot_hash` varchar(64) NOT NULL,
  `dictionary_hash` varchar(64) NOT NULL,
  `industry_level1` varchar(128),
  `industry_level2` varchar(128),
  `industry_segment` varchar(255),
  `industry_chain_position` varchar(255),
  `products` json NOT NULL DEFAULT (JSON_ARRAY()),
  `institutions` json NOT NULL DEFAULT (JSON_ARRAY()),
  `academic_links` json NOT NULL DEFAULT (JSON_ARRAY()),
  `customer_representatives` json NOT NULL DEFAULT (JSON_ARRAY()),
  `product_search_text` text,
  `product_route_search_text` text,
  `production_stage_search_text` text,
  `institution_search_text` text,
  `academic_search_text` text,
  `academic_institution_search_text` text,
  `academic_relation_search_text` text,
  `has_major_institution` boolean NOT NULL DEFAULT false,
  `has_commercialization_link` boolean NOT NULL DEFAULT false,
  `financing_status` varchar(64),
  `latest_round` varchar(64),
  `latest_round_date` date,
  `latest_amount_display` varchar(128),
  `latest_amount_value` bigint,
  `latest_amount_currency` varchar(16),
  `cumulative_amount_display` varchar(128),
  `cumulative_amount_value` bigint,
  `completed_round_count` int NOT NULL DEFAULT 0,
  `valuation_display` varchar(128),
  `valuation_value` bigint,
  `valuation_type` varchar(24),
  `valuation_currency` varchar(16),
  `valuation_date` date,
  `valuation_round` varchar(64),
  `highest_customer_stage` varchar(8),
  `verified_customer_count` int NOT NULL DEFAULT 0,
  `tier_a_customer_count` int NOT NULL DEFAULT 0,
  `tier_b_customer_count` int NOT NULL DEFAULT 0,
  `tier_c_customer_count` int NOT NULL DEFAULT 0,
  `verified_dimensions` int NOT NULL DEFAULT 0,
  `applicable_dimensions` int NOT NULL DEFAULT 0,
  `conflict_count` int NOT NULL DEFAULT 0,
  `profile_status` varchar(24) NOT NULL DEFAULT 'missing',
  `source_fact_ids` json NOT NULL DEFAULT (JSON_ARRAY()),
  `facts_updated_at` datetime(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`lead_id`),
  CONSTRAINT `fk_lead_investment_profile_lead` FOREIGN KEY (`lead_id`) REFERENCES `sbl_leads` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_lead_investment_profile_snapshot` FOREIGN KEY (`snapshot_id`) REFERENCES `sbl_lead_enrichment_snapshots` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `ck_lead_investment_profile_counts` CHECK (
    `completed_round_count` >= 0 AND `verified_customer_count` >= 0
    AND `tier_a_customer_count` >= 0 AND `tier_b_customer_count` >= 0 AND `tier_c_customer_count` >= 0
    AND `verified_dimensions` >= 0 AND `applicable_dimensions` >= 0
    AND `verified_dimensions` <= `applicable_dimensions` AND `conflict_count` >= 0
  ),
  CONSTRAINT `ck_lead_investment_profile_status` CHECK (`profile_status` IN ('verified','partial','conflicted','missing','not_applicable','stale')),
  CONSTRAINT `ck_lead_investment_profile_customer_stage` CHECK (`highest_customer_stage` IS NULL OR `highest_customer_stage` IN ('L0','L1','L2','L3','L4','L5')),
  INDEX `idx_lead_investment_profiles_industry` (`industry_level1`, `industry_level2`),
  INDEX `idx_lead_investment_profiles_financing` (`latest_round`, `latest_round_date`),
  INDEX `idx_lead_investment_profiles_funding_sort` (`latest_round_date`, `lead_id`),
  INDEX `idx_lead_investment_profiles_valuation` (`valuation_currency`, `valuation_value`),
  INDEX `idx_lead_investment_profiles_valuation_sort` (`valuation_value`, `lead_id`),
  INDEX `idx_lead_investment_profiles_customer` (`highest_customer_stage`, `verified_customer_count`),
  INDEX `idx_lead_investment_profiles_customer_tier_a` (`tier_a_customer_count`, `lead_id`),
  INDEX `idx_lead_investment_profiles_customer_tier_b` (`tier_b_customer_count`, `lead_id`),
  INDEX `idx_lead_investment_profiles_customer_tier_c` (`tier_c_customer_count`, `lead_id`),
  INDEX `idx_lead_investment_profiles_status` (`profile_status`, `updated_at`),
  INDEX `idx_lead_investment_profiles_updated_sort` (`facts_updated_at`, `lead_id`),
  INDEX `idx_lead_investment_profiles_institution` (`has_major_institution`)
);
