CREATE TABLE `sbl_ai_evolution_release_jobs` (
  `id` varchar(36) NOT NULL PRIMARY KEY,
  `candidate_id` varchar(36) NOT NULL,
  `approval_id` varchar(36) NOT NULL,
  `actor_user_id` varchar(36) NOT NULL,
  `environment` varchar(128) NOT NULL,
  `idempotency_key` varchar(128) NOT NULL,
  `input_hash` varchar(64) NOT NULL,
  `status` varchar(24) NOT NULL DEFAULT 'queued',
  `receipt` json NULL,
  `attempt` int NOT NULL DEFAULT 0,
  `lease_token` int NOT NULL DEFAULT 0,
  `lease_owner` varchar(128) NULL,
  `lease_expires_at` datetime(3) NULL,
  `error` json NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `completed_at` datetime(3) NULL,
  CONSTRAINT `fk_evo_release_job_candidate` FOREIGN KEY (`candidate_id`) REFERENCES `sbl_ai_evolution_candidates` (`id`),
  CONSTRAINT `fk_evo_release_job_approval` FOREIGN KEY (`approval_id`) REFERENCES `sbl_ai_evolution_approvals` (`id`),
  UNIQUE KEY `uq_evo_release_job_request` (`actor_user_id`, `idempotency_key`),
  UNIQUE KEY `uq_evo_release_job_approval` (`approval_id`),
  KEY `idx_evo_release_job_lease` (`status`, `lease_expires_at`),
  KEY `idx_evo_release_job_candidate` (`candidate_id`, `created_at`)
);
