CREATE TABLE `sbl_admin_permanent_deletions` (
  `id` varchar(36) NOT NULL PRIMARY KEY,
  `token_hash` varchar(64) NOT NULL,
  `resource_type` varchar(16) NOT NULL,
  `resource_id` varchar(36) NOT NULL,
  `resource_name` varchar(255) NOT NULL,
  `resource_version` varchar(128) NOT NULL,
  `impact_hash` varchar(64) NOT NULL,
  `impact_counts` json NOT NULL,
  `actor_id` varchar(36) NOT NULL,
  `actor_name` varchar(128) NOT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'preview',
  `risk_confirmation_version` varchar(32) NULL,
  `database_deleted_at` datetime(3) NULL,
  `file_cleanup_status` varchar(16) NOT NULL DEFAULT 'none',
  `file_cleanup_payload` json NOT NULL,
  `file_cleanup_attempts` int NOT NULL DEFAULT 0,
  `file_cleanup_error` varchar(128) NULL,
  `expires_at` datetime(3) NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY `uq_admin_permanent_deletion_token` (`token_hash`),
  KEY `idx_admin_permanent_deletion_actor` (`actor_id`,`status`,`expires_at`),
  KEY `idx_admin_permanent_deletion_resource` (`resource_type`,`resource_id`,`status`),
  CONSTRAINT `fk_admin_permanent_deletion_actor` FOREIGN KEY (`actor_id`) REFERENCES `sbl_users` (`id`) ON DELETE RESTRICT
);
