CREATE TABLE `sbl_digital_twin_publications` (`id` char(36) NOT NULL,`twin_id` char(36) NOT NULL,`owner_user_id` char(36) NOT NULL,`published_version` int NOT NULL,`introduction` text NOT NULL,`public_rules` longtext NOT NULL,`public_cases` longtext NOT NULL,`industry_tags` json NOT NULL,`capability_tags` json NOT NULL,`status` varchar(16) NOT NULL DEFAULT '已发布',`published_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),`withdrawn_at` timestamp(3),PRIMARY KEY (`id`),UNIQUE KEY `uq_digital_twin_publication_twin` (`twin_id`),KEY `idx_digital_twin_publications_directory` (`status`,`owner_user_id`),CONSTRAINT `fk_twin_publication_twin` FOREIGN KEY (`twin_id`) REFERENCES `sbl_digital_twins` (`id`) ON DELETE CASCADE,CONSTRAINT `fk_twin_publication_owner` FOREIGN KEY (`owner_user_id`) REFERENCES `sbl_users` (`id`) ON DELETE CASCADE);
--> statement-breakpoint
CREATE TABLE `sbl_digital_twin_invocation_logs` (`id` char(36) NOT NULL,`publication_id` char(36) NOT NULL,`caller_user_id` char(36) NOT NULL,`project_id` char(36),`usage` varchar(32) NOT NULL,`input_summary` text NOT NULL,`output_summary` text NOT NULL,`created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY (`id`),KEY `idx_twin_invocation_publication` (`publication_id`,`created_at`),KEY `idx_twin_invocation_caller` (`caller_user_id`,`created_at`),CONSTRAINT `fk_twin_invocation_publication` FOREIGN KEY (`publication_id`) REFERENCES `sbl_digital_twin_publications` (`id`) ON DELETE RESTRICT,CONSTRAINT `fk_twin_invocation_caller` FOREIGN KEY (`caller_user_id`) REFERENCES `sbl_users` (`id`) ON DELETE RESTRICT,CONSTRAINT `fk_twin_invocation_project` FOREIGN KEY (`project_id`) REFERENCES `sbl_projects` (`id`) ON DELETE SET NULL);
--> statement-breakpoint
CREATE TABLE `sbl_digital_twin_learning_candidates` (`id` char(36) NOT NULL,`twin_id` char(36) NOT NULL,`owner_user_id` char(36) NOT NULL,`source_file_id` char(36) NOT NULL,`source_hash` varchar(64) NOT NULL,`source_name` varchar(255) NOT NULL,`project_id` char(36) NOT NULL,`rules` longtext NOT NULL,`cases` longtext NOT NULL,`boundaries` text NOT NULL,`rationale` text NOT NULL,`status` varchar(16) NOT NULL DEFAULT '待确认',`decided_at` timestamp(3),`created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY (`id`),UNIQUE KEY `uq_twin_learning_source` (`twin_id`,`source_file_id`,`source_hash`),KEY `idx_twin_learning_owner` (`owner_user_id`,`status`,`created_at`),CONSTRAINT `fk_twin_learning_twin` FOREIGN KEY (`twin_id`) REFERENCES `sbl_digital_twins` (`id`) ON DELETE CASCADE,CONSTRAINT `fk_twin_learning_owner` FOREIGN KEY (`owner_user_id`) REFERENCES `sbl_users` (`id`) ON DELETE CASCADE,CONSTRAINT `fk_twin_learning_file` FOREIGN KEY (`source_file_id`) REFERENCES `sbl_project_files` (`id`) ON DELETE RESTRICT,CONSTRAINT `fk_twin_learning_project` FOREIGN KEY (`project_id`) REFERENCES `sbl_projects` (`id`) ON DELETE RESTRICT);
--> statement-breakpoint
CREATE TABLE `sbl_digital_twin_skills` (`id` char(36) NOT NULL,`twin_id` char(36) NOT NULL,`owner_user_id` char(36) NOT NULL,`name` varchar(128) NOT NULL,`active_version` int NOT NULL DEFAULT 0,`status` varchar(16) NOT NULL DEFAULT '试用中',`created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),`updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY (`id`),UNIQUE KEY `uq_twin_skill_twin` (`twin_id`),KEY `idx_twin_skill_owner` (`owner_user_id`,`updated_at`),CONSTRAINT `fk_twin_skill_twin` FOREIGN KEY (`twin_id`) REFERENCES `sbl_digital_twins` (`id`) ON DELETE CASCADE,CONSTRAINT `fk_twin_skill_owner` FOREIGN KEY (`owner_user_id`) REFERENCES `sbl_users` (`id`) ON DELETE CASCADE);
--> statement-breakpoint
CREATE TABLE `sbl_digital_twin_skill_versions` (`id` char(36) NOT NULL,`skill_id` char(36) NOT NULL,`version` int NOT NULL,`trigger` text NOT NULL,`instructions` longtext NOT NULL,`checklist` json NOT NULL,`output_format` text NOT NULL,`boundaries` text NOT NULL,`source_candidate_id` char(36),`status` varchar(16) NOT NULL DEFAULT '试用中',`created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY (`id`),UNIQUE KEY `uq_twin_skill_version` (`skill_id`,`version`),CONSTRAINT `fk_twin_skill_version_skill` FOREIGN KEY (`skill_id`) REFERENCES `sbl_digital_twin_skills` (`id`) ON DELETE CASCADE,CONSTRAINT `fk_twin_skill_version_candidate` FOREIGN KEY (`source_candidate_id`) REFERENCES `sbl_digital_twin_learning_candidates` (`id`) ON DELETE SET NULL);
