import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const read = (path: string) => readFile(new URL(`../../${path}`, import.meta.url), 'utf8')

test('independent discovery workspace keeps the existing project discovery presentation and lead pool', async () => {
  const [center, discovery, discoveryCss, sourcing, app] = await Promise.all([
    read('src/pages/ProjectCenterPage.tsx'),
    read('src/pages/ProjectDiscoveryPage.tsx'),
    read('src/pages/ProjectDiscoveryPage.css'),
    read('src/pages/SourcingPage.tsx'),
    read('src/App.tsx'),
  ])

  assert.doesNotMatch(center, /id: 'discover', label: '新项目发现'/)
  assert.match(app, /path="\/discovery" element=\{<ProjectDiscoveryPage\s*\/>\}/)
  assert.match(app, /path="\/discovery\/leads" element=\{<SourcingPage\s*\/>\}/)
  assert.match(discovery, /<h1>新项目发现<\/h1>/)
  assert.match(discovery, /今天新发现/)
  assert.match(discovery, /近 7 天/)
  assert.match(discovery, /value: 'all', label: '全部项目'/, '时间筛选应提供全部项目入口')
  assert.doesNotMatch(discovery, /label: '全部'/, '发现页不应将首页候选误标为全量')
  assert.match(discovery, /action === 'refresh' \? '开始更新' : '检查更新'/, '检查期间应立即显示开始更新状态')
  assert.match(discovery, /action === 'upload' \? '上传中' : '人工上传项目'/, '标题右侧应保留人工上传项目入口')
  assert.doesNotMatch(discovery, /刷新发现/, '页面不应保留与检查更新重复的刷新入口')
  assert.doesNotMatch(discovery, /补充发现来源/, '操作区只保留两个明确动作')
  assert.doesNotMatch(discovery, /从已收录的公开信源中/, '标题区只保留新项目发现和两个操作')
  assert.match(discovery, /<header className="project-discovery-hero">[\s\S]*<h1>新项目发现<\/h1>[\s\S]*className="project-discovery-action-buttons"[\s\S]*<\/header>/, '检查更新和人工上传项目应位于标题同一行右侧')
  assert.doesNotMatch(discovery, /<section className="project-discovery-actions"/, '不应再渲染独立的空白操作框')
  assert.doesNotMatch(discoveryCss, /\.project-discovery-actions\s*\{/, '应删除独立操作框样式')
  assert.doesNotMatch(discovery, /<section className="project-discovery-metrics"/, '不应再渲染发现概览统计卡片')
  assert.doesNotMatch(discovery, /<DiscoveryMetric/, '应删除已无用途的统计卡片组件调用')
  assert.doesNotMatch(discovery, /buildProjectDiscoverySummary/, '应删除已无用途的统计汇总计算')
  assert.doesNotMatch(discoveryCss, /\.project-discovery-metrics/, '应删除统计卡片及其响应式样式')
  assert.match(discovery, /<section className="project-discovery-results" aria-label="待查看项目"[^>]*>/, '结果卡片应保留一个带无障碍名称的外框')
  assert.doesNotMatch(discovery, /project-discovery-results-heading/, '结果外框不应再显示标题、说明或数量栏')
  assert.doesNotMatch(discoveryCss, /\.project-discovery-results-heading/, '应删除结果标题栏样式')
  assert.doesNotMatch(discovery, /\/leads\/sync-radar/, '新项目发现不得再调用原自动找项目 Agent')
  assert.doesNotMatch(discovery, /RadarSyncResult|canRunRadar|useAuthStore/, '数据库刷新不应保留 Agent 权限和结果依赖')
  assert.match(discovery, /const refreshed = await loadCandidates\(true\)/, '检查更新应直接重新读取数据库')
  assert.match(discovery, /已从数据库读取最新项目数据/, '数据库刷新完成后应明确反馈数据来源')
  assert.match(discovery, /\/leads\/bp-uploads/, '发现模块应提供人工 BP 上传入口')
  assert.match(discovery, /apiGet<[^>]+>\(`\/leads\/bp-uploads\/\$\{/, 'BP 上传后应轮询异步解析结果')
  assert.match(discovery, /`\/leads\/bp-uploads\/\$\{uploaded\.id\}\/retry`/, '失败的 BP 任务应复用既有重试接口')
  assert.doesNotMatch(discovery, /idempotencyKey:\s*crypto\.randomUUID/, '同一文件重试应由服务端内容哈希保持幂等')
  assert.match(discoveryCss, /focus-within/, '隐藏的文件输入仍需提供可见键盘焦点')
  assert.match(discoveryCss, /prefers-reduced-motion/, '加载动画应尊重减少动态效果设置')
  assert.match(discovery, /navigate\(`\/sourcing\/\$\{lead\.id\}`/)
  assert.match(discovery, /\{expanded && <footer className="project-discovery-card-actions">/, '项目操作应在展开后出现，缩略卡片保持简洁')
  assert.match(discovery, /暂不跟进/, '展开后应保留暂不跟进操作')
  assert.match(discovery, /项目入库/, '展开后应保留项目入库操作')
  assert.match(discovery, /\/project-discovery\/assignment-options/, '部门人员仅在打开入库表单时加载')
  assert.match(discovery, /归属部门/, '项目入库需选择具体部门')
  assert.match(discovery, /项目负责人/, '项目入库需选择具体负责人')
  assert.match(discovery, /ownerUserId/, '项目入库请求必须提交负责人稳定标识')
  assert.match(discovery, /department/, '项目入库请求必须提交部门')
  assert.doesNotMatch(discovery, /\/project-discovery\/leads\/\$\{lead\.id\}\/keywords/, '卡片不再展示或编辑重点关键词，原有存量数据仍保留')
  assert.match(discovery, /\/project-discovery\/leads\/\$\{lead\.id\}\/card/, '卡片业务内容必须保存到发现池专用接口')
  assert.match(discovery, /\/project-discovery\/leads\/\$\{lead\.id\}\/defer/, '暂不跟进必须写入发现池专用接口')
  assert.doesNotMatch(discovery, /project-discovery-keyword-input|编辑关键词|重点关键词/, '新卡片不呈现关键词')
  assert.match(discovery, /project-discovery-investment-brief/, '卡片应使用 VC Hunter 同款投资速览区')
  assert.match(discovery, /className="project-discovery-title-input"/, '项目名称应能在卡片原位置直接编辑')
  assert.match(discovery, /className="project-discovery-date-input"/, '融资或公开日期应能在卡片原位置直接编辑')
  assert.match(discovery, /project-discovery-fact-input\$\{item\.label/, '投资速览字段应能在卡片原位置直接编辑')
  assert.match(discovery, /className="project-discovery-summary-input"/, '展开后的项目摘要应能直接编辑')
  assert.match(discovery, /className="project-discovery-profile-input"/, '展开后的画像字段应能直接编辑')
  assert.match(discovery, /保存卡片/, '卡片编辑应提供明确的统一保存动作')
  assert.match(discovery, /展开详细信息/)
  assert.match(discovery, /收起详细信息/)
  assert.match(discovery, /!expanded && <CardDetailsToggle[\s\S]*\{expanded && <footer className="project-discovery-card-actions">[\s\S]*<CardDetailsToggle expanded/, '展开按钮只在折叠态显示，收起按钮应位于展开卡片操作区之后')
  assert.match(discovery, /项目摘要/)
  assert.match(discovery, /公司画像/)
  assert.match(discovery, /research\?\.dataStatus\?\.status/, '兼容型科研画像缺少 dataStatus 时卡片仍应可渲染')
  assert.doesNotMatch(discovery, /AI 已筛选|待审核/, '卡片顶部不应再显示 AI 已筛选或待审核徽标')
  assert.doesNotMatch(discovery, /projectDiscoveryStatusLabel\(lead\.poolStatus\)/, '卡片顶部应以融资日期取代生命周期徽标')
  assert.match(discovery, /item\.label === '最新融资日期' \|\| item\.label === '公开日期'/, '融资或公开日期应在两栏速览中直接编辑')
  assert.doesNotMatch(discovery, /buildProjectDiscoveryKeywords\(lead\)/, '卡片不再生成可见关键词')
  assert.doesNotMatch(discovery, /role="button"/, '卡片整体不应充当按钮，展开与详情操作应使用独立语义按钮')
  assert.match(discoveryCss, /project-discovery-timeline-item/, '全部项目使用统一的整行时间线布局')
  assert.match(discoveryCss, /project-discovery-investment-brief/, '投资速览应有独立的双列卡片样式')
  assert.doesNotMatch(discovery, /project-discovery-keyword-chip/, '关键词不应再使用气泡或逐个按钮')
  assert.doesNotMatch(discoveryCss, /project-discovery-keyword-chip/, '关键词不应再保留气泡样式')
  assert.doesNotMatch(discovery, /project-discovery-keyword-editor/, '关键词不应再打开独立编辑面板')
  assert.doesNotMatch(discovery, /keywordKinds/, '关键词编辑不应再提供类型筛选下拉')
  assert.doesNotMatch(discoveryCss, /project-discovery-keyword-input/, '不再保留关键词布局样式')
  assert.match(discoveryCss, /project-discovery-assignment-form/, '入库分配应在卡片内完成')
  assert.match(discoveryCss, /\.project-discovery-card-actions\s*\{[^}]*margin-top:\s*auto;/s, '同一行卡片的操作区应统一贴底')
  assert.match(discoveryCss, /\.project-discovery-card-actions button\s*\{[^}]*height:\s*38px;/s, '卡片操作按钮应使用统一固定高度')
  assert.match(sourcing, /<h1>共享线索池<\/h1>/, '原线索池仍需独立保留')
})

test('discovery workspace keeps lead-pool layout, monitoring controls and people route visible', async () => {
  const [styles, app, nav, discovery, people] = await Promise.all([
    read('src/styles.css'), read('src/App.tsx'), read('src/layout/AppLayout.tsx'),
    read('src/pages/ProjectDiscoveryPage.tsx'), read('src/pages/DiscoveryPeoplePage.tsx'),
  ])
  assert.match(styles, /\.lead-pool-hero\s*\{/)
  assert.match(styles, /\.lead-pool-filters\s*\{[^}]*repeat\(5,/s)
  assert.match(styles, /\.lead-pool-table-scroll\s*\{[^}]*overflow-x:\s*auto/s)
  assert.match(styles, /\.lead-pool-row:hover,\s*\.lead-pool-row:focus-visible/)
  assert.match(styles, /\.lead-pool-pagination\s*\{/)
  assert.match(discovery, /<DiscoveryMonitoringPanel\s*\/>/)
  assert.match(app, /path="\/discovery\/people" element=\{<DiscoveryPeoplePage\s*\/>\}/)
  assert.match(nav, /to: '\/discovery\/people', label: '人物发掘'/)
  assert.match(people, /科研人物线索，不代表创业或融资意愿/)
})

test('all discovery cards use the compact timeline layout without visible keywords', async () => {
  const [discovery, css] = await Promise.all([
    read('src/pages/ProjectDiscoveryPage.tsx'),
    read('src/pages/ProjectDiscoveryPage.css'),
  ])
  assert.match(discovery, /candidates\.map\(\(lead\) => <div[^>]*project-discovery-timeline-item/)
  assert.match(css, /\.project-discovery-grid\s*\{[^}]*grid-template-columns:\s*minmax\(0,1fr\)/s)
  assert.match(discovery, /function DiscoveryInvestmentBrief[\s\S]*item\.label === '最新融资日期'/)
  assert.doesNotMatch(discovery, /className="project-discovery-keywords"|className="project-discovery-keyword-input"/)
  assert.match(discovery, /className=\{`project-discovery-fact-input\$\{item\.label === '核心团队背景' \|\| item\.label === '核心优势' \? ' is-secondary' : ''\}`\}/)
  assert.match(css, /\.project-discovery-fact-input\.is-secondary\s*\{[^}]*font-weight:\s*400/s)
  assert.match(discovery, /\{expanded && <>[\s\S]*<footer className="project-discovery-card-actions">[\s\S]*<CardDetailsToggle expanded/)
})
